### ISSUE TITLE
Objects don't seem to be importing properly?

### ISSUE THREAD

**Issue by Haz3rd** [Unity-Technologies/2d-extras#101]
Downloaded the master zip folder, imported into my project asset folder to use the animated tile but nothing shows up in the create option, can't see any of the other tiles or brushes either, i'm using the latest version of unity 2019.3.0a2?? I'm new to all this so it's probably something simple.

**Comment by md-one** [comment]
you need to use 2019.1.4f1 or older

**Comment by ChuanXin-Unity** [comment]
Currently, master will not work with 2019.3 as it targets 2019.1, the current official release.

You can try the package/2019.2 branch to handle these changes made in 2019.2 with the Tilemap Editor package, although I have not tested it out with the current 2019.3 alpha. Please follow the instructions in the README there on how to setup 2d-extras.
