### ISSUE TITLE
Rule Tile default game object not saved

### ISSUE THREAD

**Issue by Newtonovich** [Unity-Technologies/2d-extras#104]
When creating a rule tile, and attaching a prefab to the default game object, (without tiling rules), and the RuleTile loses default data upon closing/building

**Comment by ChuanXin-Unity** [comment]
This should be fixed with c52ed0065f79e3244766e5e768a200a6eceaa392 in master.

**Comment by ChuanXin-Unity** [comment]
Thanks for pointing this out!
