### ISSUE TITLE
QUESTION: How to add RuleTile to my tile

### ISSUE THREAD

**Issue by rshmiraf** [Unity-Technologies/2d-extras#11]
Hi,
I would love to use your RuleTileEditor with my tiles. I found only solution (Robodash and Penny) where you are using it but how can I add it to my project. I'm beginner in Unity so if there is somewhere article how to implement this I would really appreciate any help. Great work anyway!

Sorry for adding this in issues but I have no idea how to ask you directly...

**Comment by ethanunity** [comment]
Hey there,

Are you wondering how to add RuleTiles to your project?

If so, do the following
1. Clone this repository (or just download it as a[ zip](https://github.com/Unity-Technologies/2d-extras/archive/master.zip)
2. Add the folder to your project, this will give you access to all the 2d-extras in this repository
3. Right click in your project view, and go Create->Rule Tile
4. Create your rules for your tile, using sprites and the editor for the rule tile
5. drag the rule tile to your palette
6. Select the rule tile in your palette and paint into your scene (Ensure you have a tilemap in your scene)

If there's anything else you need help with, let us know

Cheers,

Ethan

**Comment by rshmiraf** [comment]
That what I was looking for. Thanks a lot :)
