### ISSUE TITLE
Tools not showing up under create

### ISSUE THREAD

**Issue by Dertrock** [Unity-Technologies/2d-extras#110]
Am i missing something? I've tried installing different versions of unity with the appropriate branch and i still can't get the tools to show up in create, I've tried the techdemo as well with the appropriate version any help would be great.
![TileMap](https://user-images.githubusercontent.com/52053714/59885650-53af0c80-9392-11e9-9577-38d932e3f26a.png)

**Comment by ChuanXin-Unity** [comment]
It looks like you are using Unity 2018.2. You will need to use the 2018.2 branch of this repository to access the tools. 

Also, are there any messages in the console window? Could you try right clicking the Tilemap folder and reimport it?

**Comment by Dertrock** [comment]
I got it to work using 2018.2, i deleted the Tilemap and imported the 2018.2 branch again and that seemed to fix it.  I don't think 2d-extras likes it when you downgrade a current project to 2018.2 then use the 2018.2 branch, it won't work that way but if i start a new project under the 2018.2 branch it'll work.  Thanks
