### ISSUE TITLE
Collision detection problem threw code.

### ISSUE THREAD

**Issue by Sicmish** [Unity-Technologies/2d-extras#111]
This really isn't a issue.
Physics2D.OverlapCircle doesn't detect the RuleTiles instantiated gameobject from void start(), perhaps  add the instantiation scripts execution order higher from import by default.
And could I get the name of that script that handles it so I can change the order manually please?

**Comment by ChuanXin-Unity** [comment]
The Instantiated GameObject is created on the first frame after the Tilemap is loaded in the scene. It could be possible that calling Physics2D.OverlapCircle from Start() in a MonoBehavior could be too early.
