### ISSUE TITLE
Coordinate Brush Z Position

### ISSUE THREAD

**Issue by pmurph0305** [Unity-Technologies/2d-extras#112]
Coordinate Brush's z-position currently uses it's own integer instead of the Tile Palettes default Z Position field. Changing the Tile Pallete's default Z Position field with the shortcut keys, or manually, does not effect the coordinate brush. Only changing the z position field that the custom coordinate brush adds to the Tile Pallete window effects the brush and display.

This is particularly an issue when using an Isometric Z as Y tilemap.

I feel this is incorrect behavior and the brush should use Tile Pallete's included Z Position field.

**Comment by ChuanXin-Unity** [comment]
Updated and merged in the changes. Thanks!
