### ISSUE TITLE
Weighted Random TIle, can't set collider to none

### ISSUE THREAD

**Issue by gummby8** [Unity-Technologies/2d-extras#115]
Nav2d works by checking the tile collider if it is set to sprite or none, The Weighted Random Tile seems to be permanently set to Sprite.

**Comment by ChuanXin-Unity** [comment]
Hi, I have updated the editors for Random Tile and Weighted Random Tile in a1f7f028bc86625aac31f757adea188ed0cfd9f2 to include the Collider Type field for these Tiles. Hope that helps!
