### ISSUE TITLE
Infinitely creating layers while using rule brush

### ISSUE THREAD

**Issue by chrishull91** [Unity-Technologies/2d-extras#119]
Created basic scene in 2019.2.0f1
imported a small sample of tiles and set up a new rule brush using just a few of these.
Upon painting one cell in my grid the rule brush starts generating layers infinitely until unity hard stops.
![image](https://user-images.githubusercontent.com/31784074/62430241-dba16980-b6e7-11e9-91c9-eb39926badb5.png)

**Comment by ChuanXin-Unity** [comment]
Could you file a bug report with your project using the Unity Bug Reporter and post the case number here? That would be very helpful, thanks!

Without the project, I would like to check with you on the properties of your Rule Tile. Is there a GameObject Prefab attached to it instantiating a Tilemap Prefab with that Rule Tile?

**Comment by chrishull91** [comment]
I can do that when I get back home later today. 
I did the right click menu to create the rule tile from the tiles menu. Added the prefab it asks for, which I believe is a palette?, added the default at the top and a few lines of situations while filling in the 3x3 grids. If that helps

**Comment by chrishull91** [comment]
Case 1174530.

**Comment by ChuanXin-Unity** [comment]
I replied through the Unity Bug Reporter service, hope that helps!
