### ISSUE TITLE
 [LineBrush] Tiles disappear after selection and drag

### ISSUE THREAD

**Issue by BoonKiangTan** [Unity-Technologies/2d-extras#121]
How to reproduce:
1. Paint a single or couple of tiles using LineBrush
2. Using selection tool, select the painted tiles
3. Select Move Selection Tool, drag and move the selection
4. Tiles disappear after dragging a second time

Expected result: The selected tiles should not disappear
Actual result: The selected tiles disappeared

Reproducible with: 2020.1.0a1

Notes:
- In docs version (https://docs.unity3d.com/Manual/Tilemap-ScriptableBrushes-Example.html), tiles disappear on the first drag.

**Comment by ChuanXin-Unity** [comment]
Fixed in https://github.com/Unity-Technologies/2d-extras/commit/e63cd31b6ff6f5befbf37bb3b9d401045fb36126
