### ISSUE TITLE
Assembly has reference to non-existent assembly 'GUID:613783dc1674e844b87788ea74ede0f6' (Assets/Plugins/2d-extras-master/Editor/Unity.2D.Tilemap.Extras.Editor.asmdef)

### ISSUE THREAD

**Issue by GamingNub69** [Unity-Technologies/2d-extras#125]
I installed 2D extras and instantly got this error ( in the title ) I didn't change anything.

**Comment by Gilgul46** [comment]
hi there, I had the same problem but then discovered that I'm using an older version of Unity (2018.4.8f1). Check it in your unity Hub and upgrade if necessary. I'm currently using 2019.1.14f1 and its working great.
