### ISSUE TITLE
Bug in Random.Range using RandomTile

### ISSUE THREAD

**Issue by maurojunior2011** [Unity-Technologies/2d-extras#126]
When I put a RandomTile using the code below (method PlaceGround), in the next method (placePath) Random.Range always generates a single value ....

If I don't put RandomTile, Rando.Range works normally.

`
public RandomTile grounds;
public RuleTile path;

private int boundX = -9;
    private int boundY = -5;
    private int sizeX = 18;
    private int sizeY = 10;
`
public void placeGround()
    {
        for (int y = boundY; y < boundY + sizeY; y++)
        {
            for (int x = boundX; x < boundX + sizeX; x++)
            {
                if(mapGround.GetTile(new Vector3Int(x,y,0)) == null) {
                    mapGround.SetTile(new Vector3Int(x, y, 0), grounds);
                }
            }
        }
        //WeightedRandomTile t = grounds[tile];
    }

    public void placePath()
    {
        int Bx = boundX + sizeX - 1;
        int By = boundY + sizeY - 1;

        int _y = Random.Range(boundY+2, boundY + sizeY - 2);
        Debug.Log(_y + " <> " + (boundY + 2) + " <> " + (boundY + sizeY - 2));

        for(int i=boundX-1; i<= Bx+1; i++)
        {
            mapPath.SetTile(new Vector3Int(i, _y, 0), path);
        }
    }
`
[LevelManager.txt](https://github.com/Unity-Technologies/2d-extras/files/3632118/LevelManager.txt)

**Comment by ChuanXin-Unity** [comment]
The RandomTile sets a seed state value for the random number generator which helps to create a fixed pseudo-random number generator for its Tile properties. This will cause the next Random.Range value you call for placePath() to have a fixed value.

We will fix this by saving and restoring the seed state when placing a RandomTile.

**Comment by ChuanXin-Unity** [comment]
Updated at https://github.com/Unity-Technologies/2d-extras/commit/cc25c1f146525e35f7f23f786193a8a05d5f33f6
