### ISSUE TITLE
RuleTile MirrorX and MirrorY generate incorrect colliders

### ISSUE THREAD

**Issue by myko** [Unity-Technologies/2d-extras#13]
I'm using RuleTile with some rules using Collider set to Grid and MirrorX and MirrorY, this causes the colliders created by a combination of TileMapCollider2D and CompositeCollider2D to be incorrect. (Because of the negative scaling.)

**Comment by ChuanXin-Unity** [comment]
Hi, this should have been fixed in the 2017.3.0f3 release. Sorry for the inconvenience!
