### ISSUE TITLE
SibblingTile not working with OverrideRuleTile

### ISSUE THREAD

**Issue by superfrantv** [Unity-Technologies/2d-extras#132]
Hello,

i create a Sibblingtile with sibbling Group (from the Sample Sibbling Tile Script) and make a OverrideRuleTile from that SibblingTile, the sibbling Group Do Not work.

How to fix that`?

**Comment by superfrantv** [comment]
Nobody knows about it?

**Comment by superfrantv** [comment]
public class MyTile : RuleTile<MyTile.Neighbor> {
	public List<TileBase> sibings = new List<TileBase>();
	public class Neighbor : RuleTile.TilingRule.Neighbor {
		public const int Sibing = 3;
	}
	public override bool RuleMatch(int neighbor, TileBase tile) {
		switch (neighbor) {
			case Neighbor.Sibing: return sibings.Contains(tile);
		}
		return base.RuleMatch(neighbor, tile);
	}
}

how to implement this, to use in override tile?

**Comment by johnsoncodehk** [comment]
Can you upload or send me your SibblingTile and OverrideTile assets? I will check this problem.

**Comment by johnsoncodehk** [comment]
This update may solve your problem: https://github.com/Unity-Technologies/2d-extras/pull/134

**Comment by superfrantv** [comment]
how can i update?

**Comment by johnsoncodehk** [comment]
Wait to marge the pull request, or change the git url in ```Packages/manifest.json``` to:
```json
"com.unity.2d.tilemap.extras": "https://github.com/johnsoncodehk/2d-extras.git#rule-override-tile-patch-2"
```

**Comment by ChuanXin-Unity** [comment]
Merged to master! Thanks again for helping with this!
