### ISSUE TITLE
Make RuleTileEditor public

### ISSUE THREAD

**Issue by sasjafor** [Unity-Technologies/2d-extras#135]
It would be great if RuleTileEditor was public, so that I can write an editor script that inherits from RuleTileEditor to add more elements, or is there another way to do this that I'm missing?

**Comment by ChuanXin-Unity** [comment]
Yes, it is possible for RuleTileEditor to be public.

**Comment by ChuanXin-Unity** [comment]
Updated at https://github.com/Unity-Technologies/2d-extras/commit/82936cb343d051195cdaa1e83ae478ffead960a2
