### ISSUE TITLE
Add MirrorXY transform rule

### ISSUE THREAD

**Issue by johnsoncodehk** [Unity-Technologies/2d-extras#142]
```Rotated``` overlaps with ```MirrorXY``` matching rule, but in some sprite cases, mirroring is more reasonable than rotation to display.
![image](https://user-images.githubusercontent.com/16279759/67723360-c3a36280-fa16-11e9-906e-0e27476a8287.png)

**Comment by ChuanXin-Unity** [comment]
Do you mean a new Transform rule which has XY mirroring for the rotations?

**Comment by johnsoncodehk** [comment]
Yes, it is not like a rotation, but rather a combination of ```MirrorX``` and ```MirrorY```.

**Comment by johnsoncodehk** [comment]
Thank you for your work! I submitted a related patch! https://github.com/Unity-Technologies/2d-extras/pull/148
