### ISSUE TITLE
Rule Tiles "Rotated" Rule seems to be forgotten on game start for Game Objects

### ISSUE THREAD

**Issue by TheNightglow** [Unity-Technologies/2d-extras#143]
You can set a rule in a Rule Tile to be "Rotated", so you can avoid creating for every rotation an own rule, instead the placed Tile with its Sprite and attached Game Object are rotated, if the rule fits rotated

In the unity editor, this seems to work fine for me, untill I click the play button, which results in the tile map forgetting the rotation of the Game Objects 

here an example:
Befor clicking Play:
![](https://i.imgur.com/mUnai8I.png)
After clicking Play:
![](https://i.imgur.com/dZE6eUs.png)

The bigger island in the middle/top uses a variation of the rule tile, 

the island on the right uses the rule tile as it is right now in master

the island on the left uses a rule tile, but instead of the "Rotated" option, it defines for every rotation an own Rule, and supplies it with a rotated variation of the needed Prefab

Am I doing something wrong?

**Comment by johnsoncodehk** [comment]
Fixed in commit: https://github.com/Unity-Technologies/2d-extras/pull/140/commits/056d4a893efb76e15da1cdbea975ca842cdb462d

**Comment by TheNightglow** [comment]
thx, works fine
