### ISSUE TITLE
Cannot Save Default GameObject on Inspector

### ISSUE THREAD

**Issue by lazism** [Unity-Technologies/2d-extras#147]
![Honeycam 2019-10-31 18-06-54](https://user-images.githubusercontent.com/11345635/67933745-ca45fb80-fc09-11e9-8dae-5523f3519dc1.gif)

hi.
Modifying data such as "default GameObject" or "default sprite" cannot be saved.

When I reopen the project right after setting it up and save project, it reverted.
After deleting the Unity Engine, I tried to update it to 2018.4.12f1 but it didn't work.
The only way to save data is to force setup in the debug window.

and I using 2d-extras-2018.3 latest release version.

**Comment by ChuanXin-Unity** [comment]
I will take a look for this issue!

**Comment by lazism** [comment]
Finally! It's working now. Thank you.

2019년 11월 6일 (수) 오후 6:09, ChuanXin-Unity <notifications@github.com>님이 작성:

**Comment by lazism** [comment]
I missent the message. I'm sorry.

2019년 11월 7일 (목) 오전 2:29, Yongs KR <jung2goon@gmail.com>님이 작성:

**Comment by ChuanXin-Unity** [comment]
> Finally! It's working now. Thank you.

Does it work for you on master? It seems ok on master for me. 

Just to check, when changing Default GameObject or Default Sprite, did you use "File/Save Project" to save the changes? Using "File/Save" will not save assets like the Tile assets.

**Comment by lazism** [comment]
Hello, I've captured the issue in a video clip. I saved it the way you told me, but it's still stored in the DebugWindow, not just in the Inspector.

edit with inspector : 
https://www.youtube.com/watch?v=W0DMRiIyRZE

edit with debugWindow : 
https://www.youtube.com/watch?v=gA73lR2kSY4

The inspector doesn't respond when I press "SaveProject", looks as it doesn't recognize the change.

**Comment by ChuanXin-Unity** [comment]
I think I see the problem based on the videos. 

Just to confirm, are you using the 2018.3 branch of the 2d-extras repo (as you are using Unity 2018.4)?

**Comment by lazism** [comment]
> I think I see the problem based on the videos.
> 
> Just to confirm, are you using the 2018.3 branch of the 2d-extras repo (as you are using Unity 2018.4)?

Yes, i used the released source code "2d-extras-2018.3".

**Comment by ChuanXin-Unity** [comment]
Thanks for confirming that again!

I updated the 2018.3 branch with the fix:
https://github.com/Unity-Technologies/2d-extras/commit/7e4b3c90328b8e0f4c2c52bbff4f578419efb2e1

You can update the RuleTileEditor script with this changeset or retrieve the latest from the 2018.3 branch.

**Comment by lazism** [comment]
I checked. Thank you.
