### ISSUE TITLE
Rule Tile Rotation?

### ISSUE THREAD

**Issue by mikecann** [Unity-Technologies/2d-extras#15]
Firstly, great work with this. I once spent a long time doing this myself, good to see somone has done this and done it much better than I ever could have :)

So my question, I must be missing something but how do you specify that the provided sprite should be rotated on a rule?

![image](https://user-images.githubusercontent.com/215033/34324483-dc946174-e8af-11e7-9572-4e5c52953480.png)

For example in the above image note the pink area, I would like the selected sprite to be correctly rotated.

Changing the rule seems to alter the wrong one:

![image](https://i.imgur.com/YgaCS3o.gif)

Any ideas?

**Comment by ChuanXin-Unity** [comment]
The setup below could help you in this case?

![rotatedruletile](https://user-images.githubusercontent.com/29473170/34399723-22309d5c-ebc5-11e7-9d8d-8c929c77fd4d.PNG)

**Comment by mikecann** [comment]
Ahh I see so you only need one tiling rule for two configurations if you use the "Rotated" Rule?

**Comment by ChuanXin-Unity** [comment]
For this case, yes. The rule matches the tile on the left when rotated at 90 degrees and matches the tile on the right in the normal case.

This is also the same for your case in the second picture. For the tile on the left, it matches the first rule exactly. For the tile on the right, it matches the first rule when rotated at 90 degrees with the Rotated rule, so it would look as it did.  As both tiles were matched with the first rule, the second rule you set there did not take effect. The yellow lines for the Sprite then will match the transformation set in the first rule, which is vertically orientated to the top and bottom (or left to right in the 90 degrees case).

**Comment by mikecann** [comment]
Awesome, thanks for that.
