### ISSUE TITLE
Add Git tag. Update release flow and versioning.

### ISSUE THREAD

**Issue by RyotaMurohoshi** [Unity-Technologies/2d-extras#152]
Please add git tag in this repositry.
And please update release flow and versioning.

# Background

In [README.md](https://github.com/Unity-Technologies/2d-extras/tree/9f18d6679431faf3135fd54972c4ff1e5f2caeea#package-manager-manifest), downloading method with Package Manager is described as

```
"com.unity.2d.tilemap.extras": "https://github.com/Unity-Technologies/2d-extras.git#master"
```

By the way, master breanch will be updated.

Now, master is 9f18d6679431faf3135fd54972c4ff1e5f2caeea. But master was 41e47706b50cac8ecf763b745cb2ae5808968c3f only few days ago.

So my `package.json` file was updated automatically in this few days

from 

```
{
  "dependencies": {
    "com.unity.2d.sprite": "1.0.0",
    "com.unity.2d.tilemap": "1.0.0",
    "com.unity.2d.tilemap.extras": "https://github.com/Unity-Technologies/2d-extras.git#master",
    ~~~
  },
  "lock": {
    "com.unity.2d.tilemap.extras": {
      "hash": "41e47706b50cac8ecf763b745cb2ae5808968c3f",
      "revision": "master"
    }
  }
}
```

to

```
{
  "dependencies": {
    "com.unity.2d.sprite": "1.0.0",
    "com.unity.2d.tilemap": "1.0.0",
    "com.unity.2d.tilemap.extras": "https://github.com/Unity-Technologies/2d-extras.git#master",
    ~~~
  },
  "lock": {
    "com.unity.2d.tilemap.extras": {
      "hash": "9f18d6679431faf3135fd54972c4ff1e5f2caeea",
      "revision": "master"
    }
  }
}
```

This update is unexpected and not good.

And I want to use this library with a specified version, not auto updated version.

# Suggestion1 : Add Git tag.

To avoid this unexpected update, I think it is good to use git tag in `package.json` like next,

```
"com.unity.2d.tilemap.extras": "https://github.com/Unity-Technologies/2d-extras.git#1.3.0"
```

By the way, there are only tags for older unity versions.

So please add Git tag at version up.

And please consider to add git tag with next revisions,

* Please add git tag `1.2.0` to 9badd6ae9fe7487601d2e79f5c2ff0a454cfb967.
* Please add git tag `1.3.0` to 41e47706b50cac8ecf763b745cb2ae5808968c3f.

With above tag, we can use specified version 2d-extras.

# Suggestion2 : Please update release flow and versioning.

According Changelog for version 1.1.0, there are 3 versions without version up.
I think it is good to bump versions each time and add git tag to each version.

And 9f18d6679431faf3135fd54972c4ff1e5f2caeea was so nice bug fix.
I think it is so good to bump patch version from 1.3.0 to 1.3.1 and add CHANGELOG.md and Git tag..

# Message

I love tilemap and 2d-extras.
And I think it is so good and useful to introduce 2d-extras via package manager.
With git tag, it is so easy and clearly to download specified version 2d-extras.

Please consider add Git tag and update release flow and versioning.

**Comment by ChuanXin-Unity** [comment]
This is a good idea and a nice reminder for utilizing the tags function! I will tag the missing versions.

We will keep this in mind when updating new versions! Also, we hope to have this in the Unity package manager as well soon.

>

**Comment by RyotaMurohoshi** [comment]
Thanks!
So nice! I can use Git tag to install 2d-extras.

> we hope to have this in the Unity package manager as well soon.

Oh, really? Sounds great! I am looking forward to use from Unity package manager.

**Comment by johnsoncodehk** [comment]
I think we should not assign a version number immediately for each small fixes commit, because git package do not support the version format like ```1.3.x```, too discrete version numbers can cause problems for users.

I recommend keeping the small fixes in the master(latest) version, and it is reasonable to assign the version number in the following three cases:
1. A certain number of small fixes have been accumulated.
2. Before commit or marge a big change. (Must)
3. No other updates for a long time.

**Comment by ChuanXin-Unity** [comment]
@johnsoncodehk 

I agree, we will generally wait for an amount of fixes before updating for a new version. The other times when we would change the version immediately would be when there are new or breaking features in the code here.
