### ISSUE TITLE
Isometric rule tiles inverted

### ISSUE THREAD

**Issue by moutoum** [Unity-Technologies/2d-extras#153]
Hi,
I'm trying to use the isometric rule tile feature you provide, and I'm facing a very strange problem:
I associated all my sprites to a rule, but it seems the X axis is inverted when i'm using it.

![stack1](https://user-images.githubusercontent.com/16138202/68703632-500f6280-058b-11ea-8580-85ba6bc8ca6b.PNG)

For example, this is my top-left and bottom-right borders definitions:
![stack2](https://user-images.githubusercontent.com/16138202/68703650-57cf0700-058b-11ea-8cc0-ef1d37e7a56d.PNG)

It is my first time with your library, so maybe I missed something.
Otherwise, did you already face this problem before ?

Thank you in advance for your help !

**Comment by johnsoncodehk** [comment]
Thank you for your report!
The problem has been fixed by https://github.com/Unity-Technologies/2d-extras/pull/154/commits/898b3d63ae5046c14f6c4113928f73023699c3e5.

**Comment by moutoum** [comment]
Thank you @johnsoncodehk  for your reactivity!
