### ISSUE TITLE
Can I use "SetEditorPreviewTile" method at Runtime?

### ISSUE THREAD

**Issue by lazism** [Unity-Technologies/2d-extras#160]
It looks like "SetPreviewTile" is made for palette, or brush. 
I want to know what's different from SetTile internally, or Is it simply a function of layer division?

I want to implement functions such as the palette of Unity in myGame, Is it okay to use this method for implementation?

**Comment by ChuanXin-Unity** [comment]
Unfortunately, no. `SetEditorPreviewTile` is only available in Editor and specifically sets the Tile to an Editor Preview layer.
