### ISSUE TITLE
Replace the expensive IsTilemapUsedTilesChange() method

### ISSUE THREAD

**Issue by johnsoncodehk** [Unity-Technologies/2d-extras#163]
```IsTilemapUsedTilesChange()``` is use to check a tilemap cache neighbor positions if need update, it will call by ```RuleTile.RefreshTile()``` every time.

I found this method in Tilemap source code:
```csharp
internal static void SetSyncTileCallback(Action<Tilemap, SyncTile[]> callback)
```

Is it possible to get a callback when used tile changed?
If yes, can you make this method and SyncTile public? I will update the caching logic to speedup ```RuleTile.RefreshTile()```.

**Comment by ChuanXin-Unity** [comment]
Yes, this will be public in 2020.1 (possibly for 2019.3 but after its release first).

The callback will be activated when Tiles have been changed using "Tilemap.RefreshTile" after all the changes are done (after "TileBase.GetTileData" has been called for each Tile that changed).  Is that useful enough for this?

**Comment by johnsoncodehk** [comment]
I'm not sure, I expect I can know if Tilemap used tiles array changed instead of checking each time, such as adding a hash / version number / changed callback for used tiles array.
I will check the SetSyncTileCallback() when that is public, Thank you!
