### ISSUE TITLE
Tiles disappearing while painting with Prefab Brush (Hexagonal tilemap only).

### ISSUE THREAD

**Issue by GyroZeppeli7** [Unity-Technologies/2d-extras#169]
While painting an Hexagonal tilemap using the prefab brush, some tiles constantly disappear. I'll link you a gif to explain what's happening. https://gfycat.com/deadlyoptimalcoqui

**Comment by ChuanXin-Unity** [comment]
Will check this out!

**Comment by ChuanXin-Unity** [comment]
Should be fixed with this changeset: https://github.com/Unity-Technologies/2d-extras/commit/332240fe88c159d0561808de3b40f50722064efb

**Comment by GyroZeppeli7** [comment]
It works now, thanks!
