### ISSUE TITLE
GameObject Brush

### ISSUE THREAD

**Issue by truoss** [Unity-Technologies/2d-extras#17]
Thanks Guys for your work. I´m trying to create a forest with trees 3x1 tiles high.  And want to be able to place them one tile behind. so I think the GameObject Brush would do what  i would like to achieve. But how do these type of brush work, or how do i even create one.

thanks for your help.

**Comment by BeardlessDev** [comment]
If you've not figured this out by now, you change the brush in the Tile Palette menu on the bottom left. It's demonstrated in [this video](https://unity3d.com/learn/tutorials/topics/2d-game-creation/custom-tilemap-brush-spawn-prefabs).

And if you want to create them behind other tiles, just:

1. Add another 'Tilemap' to the 'Grid' object in the Scene Heirarchy
2. Change the 'Order in Layer' in the 'Tilemap Renderer' component

Hope this helps!
