### ISSUE TITLE
In Unity 2019.1, 2d-extras has a Tilemap Editor dependency which cannot be resolved

### ISSUE THREAD

**Issue by mkstarr** [Unity-Technologies/2d-extras#175]
First off, in the README, for older versions of Unity you say to "use the tag" [tag]. What do you mean by that? To replace #master with #[tag]? It is unclear, and I don't know what to do to adjust for my version of unity.

Trying to resolve the dependency doesn't work. Check out the google hits for it. It says to use the package manager, but then it's not available in the package manager, and there's no direct download. So the dependency can't be resolved.

I'm trying to solve this by downloading the most recent stable of unity.

**Comment by ChuanXin-Unity** [comment]
For 2019.1 and prior releases, they are not in the Unity Package format. They are set up as Unity Projects which you can open or copy to your own project.

![image](https://user-images.githubusercontent.com/29473170/72699982-663a3000-3b85-11ea-8fd6-9f8f637ad520.png)

If you expand the branches drop-down and switch to the tags section, you can choose the correct changeset to download the version of the 2d-extras repository that would work for you.

Alternatively, the `package` branch of this repository may work for you if copied to the Packages folder of your project.
