### ISSUE TITLE
Error when editing Packages Manifest JSON

### ISSUE THREAD

**Issue by BluishGreenProductions** [Unity-Technologies/2d-extras#176]
The setup instructions advise;

> The following line needs to be added to your Packages/manifest.json file in your Unity Project under the dependencies section:
> "com.unity.2d.tilemap.extras": "https://github.com/Unity-Technologies/2d-extras.git#master"

Doing so causes the following error in Unity 2019.3.0f3:

> Failed to resolve packages: The file [_pathName_\Packages\manifest.json] is not valid JSON:
>   Unexpected token 'c' at 43:3

Tested in a completely blank project with no other modifications made to the Manifest JSON

**Comment by ChuanXin-Unity** [comment]
Could you share the manifest.json file which causes the error?

A correct manifest.json file would look something like this:
https://github.com/Unity-Technologies/2d-techdemos/blob/master/Packages/manifest.json

**Comment by BluishGreenProductions** [comment]
Thank you, I realize my original issue was due to not adding a comma to the new line. However, even trying to copy-paste from the file you shared, the 2D Tilemap extras does not show up in the list of available packages, and when I checked my Packages Manifest, the following lines appeared in the file:
`,
  "lock": {
    "com.unity.2d.tilemap.extras": {
      "revision": "master",
      "hash": "a95c07ac963132f767842418cb3b7c260d9c8cad"
    }
  }`
Is this supposed to happen? I don't see these lines in the file you shared. I can close this issue and open a new one if that would be more appropriate.

**Comment by ChuanXin-Unity** [comment]
Yes, that should happen. This means that you have managed to download the latest version of this repository for your project.

Are you able to access the features of the 2D extras? If not, are there any console errors or logs after importing the package?

**Comment by BluishGreenProductions** [comment]
Oh heck, I kept assuming adding this line would have something show up in the Package Manager or some folder under the Packages folder, but indeed, I am able to create Rule tiles and use other features of 2D extras. Thanks again for all your help!
