### ISSUE TITLE
Prefab Brush worked once, now does not work at all

### ISSUE THREAD

**Issue by mkstarr** [Unity-Technologies/2d-extras#177]
I made a new Prefab Brush with my prefab of interest and at one point it painted just fine in Edit mode. Now, with Edit mode on, several days later, it does not paint anything at all. The prefab is selected in the brush in the Tile Palette.

![screenshot](https://user-images.githubusercontent.com/1696210/73144171-9edf7b00-4057-11ea-8097-4ee787a3c954.png)

**Comment by ChuanXin-Unity** [comment]
Hi, I answered in the forums but I will re-post it here:

Just to check, are you trying to use the Prefab brush on the Tile Palette? That is currently not supported yet for Unity 2019.2, and you can only use it on Grid/Tilemaps in the SceneView.
