### ISSUE TITLE
WeightedRandomTile breaks Random.seed, doesnt return state.

### ISSUE THREAD

**Issue by TrentSterling** [Unity-Technologies/2d-extras#178]
WeightedRandomTile uses 

`Random.InitState((int) hash);`

to set a seed but fails to return it to its original state when its finished. This breaks projects for people who are doing procedural generation. (It resets the seed I already set!)

I noticed that RandomTile doesn't have this issue. So I poked around inside, and saw that it saves the current `Random.state`, and then sets the state back up when its finished doing its thing.

Ive attached a modified version of the WeightedRandomTile that fixes this, using a snippet I took from RandomTile.

[WeightedRandomTile.txt](https://github.com/Unity-Technologies/2d-extras/files/4126576/WeightedRandomTile.txt)

**Comment by ChuanXin-Unity** [comment]
Thanks for helping out with this!
