### ISSUE TITLE
I get this Error :(

### ISSUE THREAD

**Issue by Hactavius** [Unity-Technologies/2d-extras#182]
An error occurred while resolving packages:
  Package com.unity.2d.tilemap.extras@https://github.com/Unity-Technologies/2d-extras.git#master has invalid dependencies:
    com.unity.2d.tilemap: Package [com.unity.2d.tilemap@1.0.0] cannot be found

A re-import of the project may be required to fix the issue or a manual modification of C:/Users/Username/Documents/Unity Pros/ProjectName/Packages/manifest.json file.

Please Help!

**Comment by ChuanXin-Unity** [comment]
Which version of the Unity Editor are you using? The master branch works only with Unity 2019.2 and above.

**Comment by Hactavius** [comment]
I am using Unity 2018.4 and the 2018.3 branch.

**Comment by ChuanXin-Unity** [comment]
When using the 2018.3 branch, you will need to use the repository as a project or copy out the items in the Assets folder to your existing project. 

To resolve the issue you are getting, you will need to edit your Packages/manifest.json file and remove the com.unity.2d.tilemap entry. Unity 2018.4 has the Tilemap Editor built-in and does not require a package entry.

**Comment by Hactavius** [comment]
Ahhhh thank you very much!
