### ISSUE TITLE
Getting some Errors after import

### ISSUE THREAD

**Issue by DavidDecraene** [Unity-Technologies/2d-extras#193]
1. cloned the github repository into Packages/com.unity.2d.tilemap.extras 
2. Added to the manifest.json:   "com.unity.2d.tilemap.extras": "https://github.com/Unity-Technologies/2d-extras.git#master"

Console logs 38 errors, all from the Editor folder which cant seem to resolve the RunTime implementations:

E;g; Error all of this kind:
Packages\com.unity.2d.tilemap.extras\Editor\Tiles\HexagonalRuleTile\HexagonalRuleTileEditor.cs(6,26): error CS0246: The type or namespace name 'HexagonalRuleTile' could not be found (are you missing a using directive or an assembly reference?)

Packages\com.unity.2d.tilemap.extras\Editor\Tiles\RuleTile\RuleTileEditor.cs(143,39): error CS0246: The type or namespace name 'RuleTile' could not be found (are you missing a using directive or an assembly reference?)
etc etc

I can see the source files under Packages\com.unity.2d.tilemap.extras\Runtime\Tiles

**Comment by DavidDecraene** [comment]
Fixed by using package manager instead and providing the git url there

**Comment by DryreL** [comment]
Same problem here, I used package manager
2021.1.7f1

**Comment by ChuanXin-Unity** [comment]
> Same problem here, I used package manager
> 2021.1.7f1

Hi, could you share the package version you are using from the Package Manager? Thanks!

**Comment by DryreL** [comment]
Thanks, it solved my problem!
