### ISSUE TITLE
How is this imported?

### ISSUE THREAD

**Issue by mdeforge** [Unity-Technologies/2d-extras#2]
Can't import asset, new package, or drag and drop... Not sure how to include this in my project?

**Comment by JuhaUnity** [comment]
Download and unzip files into your project folder.

**Comment by manicmario82** [comment]
Hi guys. I don't know what I'm doing wrong here but unzipping files won't work for me, no matter which Unity version is used. I have really standard folders structure but maybe 2d extrasss should be placed in specific folder (or separate folders?) Right now I can only see Default Brush and basic Tile to chose form Assets->Create menu. I have no clue how to expand editor functionality to include 2d extras. Can you have a look and help me with that please?

![unity_2018 2 0b4_personal_ 64bit _-_mario_test uni_2018-05-25_23-03-12](https://user-images.githubusercontent.com/17147360/40568014-f2e674ac-606f-11e8-97be-1f1c7f589d7d.png)
