### ISSUE TITLE
Programmatically generated RuleTiles don't render

### ISSUE THREAD

**Issue by hammackj** [Unity-Technologies/2d-extras#21]
Hi, I am programmatically building a map using RuleTiles and RandomTiles. "Floor" is a random tile and "Walls" is a RuleTile. Each work fine when I manually draw them on a map. Programmatically the wall tiles don't seem to be generated. If I swap out "Walls" with any other Tile i have it renders fine.

My question is is there anything with the RuleTile that would prevent it from working pragmatically? Is there a better way to do what I am doing?

**Also Tile.SetColor() doesn't seem to work at all in WebGL.**

```
foreach (Cell cell in dungeonMap.GetAllCells())
{
    Vector3Int tile = new Vector3Int(cell.X, cell.Y, 0);

    if (cell.IsWalkable)
    {
        Tile t = Resources.Load("Floor") as Tile;

        tilemap.SetTile(tile, t);
        tilemap.SetTileFlags(tile, TileFlags.None);
    }
    else
    {
        Tile t = Resources.Load("Walls") as Tile;

        tilemap.SetTile(tile, t);
        tilemap.SetTileFlags(tile, TileFlags.None);
    }
}
```

Thank you.

**Comment by hammackj** [comment]
I never changed my cast from Tile to RuleTile when I went from static tiles to the RuleTIle.

**Comment by ethanunity** [comment]
Hi there,

You can always use TileBase instead of having to specify the specific tile type

**Comment by hammackj** [comment]
Ah Thanks. Any word on SetColor() being fixed in WebGL? There was a tracker post on the issue site but it said it was fixed, not sure what version fixes it. It is not the current one.
