### ISSUE TITLE
Outdated help/doc links 

### ISSUE THREAD

**Issue by xjjon** [Unity-Technologies/2d-extras#211]
Some of the classes have broken / outdated doc links

https://github.com/Unity-Technologies/2d-extras/blob/master/Runtime/Tiles/AnimatedTile/AnimatedTile.cs
https://github.com/Unity-Technologies/2d-extras/blob/master/Runtime/Tiles/IsometricRuleTile/IsometricRuleTile.cs#L24

Some of them seem to have docs still like (https://docs.unity3d.com/Manual/Tilemap-Hexagonal.html) but for Iso / animated I can't seem to find the correct docs for it

**Comment by ChuanXin-Unity** [comment]
The links in the classes will be published online once this package is available on the Unity Package Manager. Unfortunately, there is no ETA for that for now yet.

In the meantime, you could check out the Documentation~ folder for the appropriate documentation, eg. :
https://github.com/Unity-Technologies/2d-extras/blob/master/Documentation~/AnimatedTile.md

**Comment by xjjon** [comment]
Thanks, can close this issue then
