### ISSUE TITLE
Animated Tile speed

### ISSUE THREAD

**Issue by P-o-R-t-C-u-L-L-i-S** [Unity-Technologies/2d-extras#216]
Hello! I've added some animated tiles into a tilemap I'm using. Is it possible to change their playback speed at runtime, using script?

Many thanks.

**Comment by ChuanXin-Unity** [comment]
Could you share how you want to change their playback speed? Eg. The speed for all animated Tiles in a Tilemap, the speed of a particular type of Tile or just some Tiles at a particular location?

1. You can change Tilemap.animationFrameRate
2. You can change the speed of the Animated Tile asset and call Tilemap.RefreshAllTiles to update the Tilemap
3. You can change the speed of the Animated Tile asset and call Tilemap.RefreshTile for each position you want to update on the Tilemap

**Comment by P-o-R-t-C-u-L-L-i-S** [comment]
I'm changing all animated tiles in a Tilemap to the same speed - Tilemap.animationFrameRate works great thank you! :)
