### ISSUE TITLE
How to copy a a rule tile?

### ISSUE THREAD

**Issue by longtran2904** [Unity-Technologies/2d-extras#218]
I had a rule tile and then I made a custom one. How to copy the rule and sprite of the rule tile to the new one?

**Comment by ChuanXin-Unity** [comment]
You can copy and paste all the rules using the menu shown below:

![image](https://user-images.githubusercontent.com/29473170/91115417-c0234b00-e6bc-11ea-938d-98e64e559034.png)

**Comment by longtran2904** [comment]
Oh, thank you! I didn't know that.
