### ISSUE TITLE
What is the weight value in weighted random tile?

### ISSUE THREAD

**Issue by longtran2904** [Unity-Technologies/2d-extras#219]
From what I can tell the weight value is an int and not a float so how to assign a for example 25% value for it?

**Comment by ChuanXin-Unity** [comment]
You can place any value in there as long as that value is 25% of the sum of total weights assigned. Eg, if there are three possibilities to choose from, assigning 2, 4 and 2 to them will result in a 25%, 50% and 25% weightage to them.

**Comment by longtran2904** [comment]
Ok, thanks for replying!
