### ISSUE TITLE
Please push the code of 1.6.1-preview if exist.

### ISSUE THREAD

**Issue by RyotaMurohoshi** [Unity-Technologies/2d-extras#221]
1. Create project with Unity 2020.2.b1 
2. Add next code in manifest.json

```
 "com.unity.2d.tilemap.extras": "ssh://git@github.com/Unity-Technologies/2d-extras.git",
```

3. Open Package Manager window and open 2D Tilemap Extras.
4. Click `See other versions`

With above steps, I found 2d-extras of version 1.6.1-preview.
But there is no code for 1.6.1-preview in this repositry.

<img width="408" alt="スクリーンショット 2020-09-08 23 45 00" src="https://user-images.githubusercontent.com/1229596/92492016-db9a6400-f22d-11ea-866e-908a1b9338bd.png">

If there is 2d-extras of version 1.6.1-preview, would you push it in this repositry?

**Comment by ChuanXin-Unity** [comment]
Yes, it will be added here.

Just to note, the changes in 1.6.1-preview are only for the samples.

**Comment by RyotaMurohoshi** [comment]
Thank you!
