### ISSUE TITLE
Support Unity 2019 and Versioning Policy

### ISSUE THREAD

**Issue by RyotaMurohoshi** [Unity-Technologies/2d-extras#222]
According current latest c051b95afaf1a099a0369b70fdea19bde5d8d100 [README](https://github.com/Unity-Technologies/2d-extras/blob/c051b95afaf1a099a0369b70fdea19bde5d8d100/README.md), 2d-extras user should install tag of `1.5.0-preview` with Unity 2019.4 LTS and should not install latest version.

Latest version of Many libraries in asset store supports supported Unity version.
In my opinion, it is so good that  latest 2d-extras package supports supported LTS Unity version.

How about change Versioning and Supporting policy?

**Comment by ChuanXin-Unity** [comment]
There are some changes for 1.6.x-preview which require the Unity 2020.x editor (support for painting GameObjects on the Tile Palette), so the version change is required.

Could you clarify more on what you mean by the versioning and support policy? Thanks!

**Comment by RyotaMurohoshi** [comment]
OK! Sorry my ambiguous description.

There are many Unity users. Some of them users use LTS  release version : Unity 2018.4 or Unity 2019.4. The others use latest tech release Unity version Unity 2020.1.

With update, `2d-extras` provides 3 types of content.

* Bug fixes
* New features that do not depend on new Unity feature. They can available on not latest Unity too.
* New features that depend on new Unity feature: like painting GameObjects on the Tile Palette

As LTS version Unity user, I want to get bug fixes and new features that do not depend on new Unity feature.

By the way, with current update policy, Unity 2019.4 LTS users can not get any next bug fixes more.

So I suggest Policy1 and Policy2.

----------

Policy 1 : Support valid LTS unity and latest Unity. And release 1 version per time.

When 2d-extras new features that depend on new tech release Unity will be added, we add #ifdef UNITY_X_Y_OR_NEWER directive to the code that depends on new tech release Unity feature.
And release it for valid LTS release Unity and latest tech release Unity.

So, LTS Unity and 2d-extras users can get `Bug fixes` and `New features that do not depend on new Unity feature`.

And Latest Unity and 2d-extras users can get all of

* Bug fixes
* New features that do not depend on new Unity feature.
* New features that depend on new Unity feature.

Pros

* LTS Unity users can get `Bug fixes` and `New features that do not depend on new Unity feature`.
* Release only one Unity package version. It is simple way.

Cons

* Unity package code contains #ifdef UNITY_X_Y_OR_NEWER directive. It may produce complexity.

----------

Policy 2 : Backport `Bug fixes` and `New features that do not depend on new Unity feature`. And release multiple version for LTS release and katest tech relese.

With this Policy 2, 2d-extras will release multiple valid version for backport to support bugfixes.

Example.

For example, there are 2 branches and versions.

for Unity 2020 : v1.6.0
for Unity 2020 : v1.5.0

Situation A : When Bug fixes update.

```
Apply Bug fixes both 2 versions and release them with next versions.

for Unity 2020 v1.6.0 :  => v1.6.1
for Unity 2019 v1.5.0 :  => v1.5.1
```

Situation B : When New features that do not depend on new Unity feature.

```
Add new feature both 2 versions and release them with next versions.

for Unity 2020 : v1.6.0 => v1.7.0
for Unity 2019 : v1.5.0 => v1.5.1
```

Situation C : When New features that depend on new Unity feature.

```
Add new feature only latest version and release it with next versions.

for Unity 2020 : v1.6.0 => v1.7.0
for Unity 2019 : v1.5.0 (no update)
```


Pros

* LTS Unity users can get `Bug fixes` and `New features that do not depend on new Unity feature`.

Cons

* Branch models is complex.
* Version naming is not good.
* Need to release multiple versions of Unity packages.


----------


My favorite solution is Policy1.

As LTS version Unity user, I want to get bug fixes update and new features that do not depend on new Unity feature update.

Thanks.

**Comment by ChuanXin-Unity** [comment]
Thank you for clarifying!

We will try to get the bugfixes and possibly new features for the 2019.4 LTS versions now, which we have not been handling before. However, it will likely be in the form of Policy 2, which is how we are handling our other 2D packages such as 2D Animation.

If you have any concerns or ideas regarding this, do let us know!

**Comment by RyotaMurohoshi** [comment]
Thank you!

> We will try to get the bugfixes and possibly new features for the 2019.4 LTS versions now, which we have not been handling before. 

Great! So nice!
I am happy with this policy!

Thank you!
