### ISSUE TITLE
Unable to install 1.5.0 preview for Unity 2019.4.9f1

### ISSUE THREAD

**Issue by circleapps** [Unity-Technologies/2d-extras#223]
After I added 
"com.unity.2d.tilemap.extras": "https://github.com/Unity-Technologies/2d-extras.git#master" to manfest.json, I found 1.6.0 preview was installed, but there is no way for me to switch to 1.5.0 preview, see screenshot below:

![image](https://user-images.githubusercontent.com/44904628/92910772-f56cbe80-f45a-11ea-86ed-e1a05b68efac.png)

Is there anything I can do to fix this problem? According to README, for Unity 2019.4, I should use "v1.5.0-preview".

Thanks.

**Comment by RyotaMurohoshi** [comment]
@circleapps 

Please try next line.

    "com.unity.2d.tilemap.extras": "https://github.com/Unity-Technologies/2d-extras.git#1.5.0-preview",
According to last block : 1.5.0-preview.

There is no v.

**Comment by RyotaMurohoshi** [comment]
README.md was updated.

Correct tag is `1.5.0-preview`.

**Comment by circleapps** [comment]
Thanks, it works for me.
