### ISSUE TITLE
Issue in manifest file when using tag  v1.5.0-preview

### ISSUE THREAD

**Issue by Gatusko** [Unity-Technologies/2d-extras#224]
Issue using the tag **v1.5.0-preview** 
In my manefist file I added the following line 

`"com.unity.2d.tilemap.extras": "https://github.com/Unity-Technologies/2d-extras.git#v1.5.0-preview"`

As I am using Unity 2019.4.9f1 Version 

At time of adding  Unity is throwing the following exception : 

```
An error occurred while resolving packages:
  Project has invalid dependencies:
    com.unity.2d.tilemap.extras: Cannot checkout repository [https://github.com/Unity-Technologies/2d-extras.git]:
      Error when executing git command. error: pathspec 'v1.5.0-preview' did not match any file(s) known to git


A re-import of the project may be required to fix the issue or a manual modification of C:/Users/Hp/test2/Packages/manifest.json file.
```
How I can solve this issue?

**Comment by RyotaMurohoshi** [comment]
@Gatusko Please try next line.

```
    "com.unity.2d.tilemap.extras": "https://github.com/Unity-Technologies/2d-extras.git#1.5.0-preview",
```

According to last block : `1.5.0-preview`.

There is no `v`.

**Comment by Gatusko** [comment]
Worked. Closing ticket.

**Comment by RyotaMurohoshi** [comment]
README.md was updated.

Correct tag is `1.5.0-preview`.
