### ISSUE TITLE
 Change README.md about 1.5.0-preview. Or push v1.5.0-preview tag.

### ISSUE THREAD

**Issue by RyotaMurohoshi** [Unity-Technologies/2d-extras#225]
Please check next 2 issues.

* https://github.com/Unity-Technologies/2d-extras/issues/223
* https://github.com/Unity-Technologies/2d-extras/issues/224

They are same issue. They can not install 2d-extras of v1.5.0-preview.

According to [current latest README.md](https://github.com/Unity-Technologies/2d-extras/blob/c051b95afaf1a099a0369b70fdea19bde5d8d100/README.md),

> Please use the v1.5.0-preview tag for Unity 2019.2-2019.4 versions.

README.md instructs `v1.5.0-preview` tag for Unity 2019.2-2019.4.

But, there is no `v1.5.0-preview`, but there is `1.5.0-preview`. This content is a little confusing.

# Suggestion 1.

How about change README.md content about tag for 2019.2-2019.4.

Before : Please use the v1.5.0-preview tag for Unity 2019.2-2019.4 versions.
After  : Please use the 1.5.0-preview tag for Unity 2019.2-2019.4 versions.

# Suggestion 2.

Or, how about push tag `v1.5.0-preview`.

**Comment by ChuanXin-Unity** [comment]
Sorry about this inconvenience!

I have updated the README.md with the correct tag!

**Comment by RyotaMurohoshi** [comment]
Thanks:+1:

I close this issue.
