### ISSUE TITLE
When painting with rule tile in tile map, it adds other things, but works fine in the palette editor

### ISSUE THREAD

**Issue by seatoads** [Unity-Technologies/2d-extras#229]
I am new to unity so maybe this is an easy fix? I tried to look into the old/new issues but I couldn't find much since I don't know others would describe this problem.

Here is a link to a video with the problem: https://youtu.be/nDWDXo2g8f0

I tried doing this before and it actually had another issue where for some reason when I painted, the tile would repeat itself infinitely but be displaced diagonally from where I painted (it also created a bunch of layer 1s for some reason), so I started over and now this is the issue.

The thing is, let's say I place the tiles 1 by 1 (instead of holding and dragging), and then I undo it, the rule tile works. It replaces the the ones I placed with the correct ones, but it doesn't get rid of the weird broken tiles. I tried to set the default game object to the new palette I created for the rule tile but it still didn't work. 

Thanks for the help!

**Comment by ChuanXin-Unity** [comment]
Hi @seatoads, I noticed in your video that you have set the GameObject of some of the Rules to the "maze_wall" Prefab? When placing the tiles onto the Tilemap, this will instaniate the "maze_wall" Prefab onto the scene for each RuleTile that matches the Rules. I am not sure if you intended to do that for your Tilemap, depending on what the "maze_wall" Prefab is. If not, could you try removing the "maze_wall" Prefab from your Rules and try painting the Tilemap again?

**Comment by seatoads** [comment]
Oh... so that's what that does. I thought game object meant like a reference or something. Thank you for your quick response! This solved it.
