### ISSUE TITLE
Hacktoberfest

### ISSUE THREAD

**Issue by Quickz** [Unity-Technologies/2d-extras#234]
I noticed that this repository isn't participating in the Hacktoberfest. I think it would be nice if it would since it would give an extra incentive to make a contribution.

Here's a video on how to do that:
https://www.youtube.com/watch?v=znPdP0o79mU

**Comment by ChuanXin-Unity** [comment]
Looks interesting! I do have to check with Unity what the policy is for this!

**Comment by edwardrowe** [comment]
Any word on this? I'd love to make some contributions for hacktoberfest!

**Comment by ChuanXin-Unity** [comment]
Hi, sorry, still following up on this internally, but it is likely that the repository will not be tagged. However, I can add the"hacktoberfest-accepted" label to each accepted PR to ensure that your contributions will count for this!

From https://hacktoberfest.digitalocean.com/faq:
What do I do if I want to contribute to a project but it doesn’t have the hacktoberfest topic?
You can still contribute to any public GitHub repository and have it count towards your progress provided that your pull request is labeled with hacktoberfest-accepted.
