### ISSUE TITLE
How should we go about updating our copy of this library?

### ISSUE THREAD

**Issue by lrtanner** [Unity-Technologies/2d-extras#25]
I cloned this down and directly moved it into my project's codebase. Is this the correct way to use this library? Also, if I want to update, can I safely grab the latest code from the repo and overwrite the older version that is in my project?

**Comment by ChuanXin-Unity** [comment]
Yes, you can use it by cloning it into your project's codebase.

Generally, it will be ok to grab the latest code from this repository. However, the code here is dependent on the version of Unity used (generally, the latest version available). If there are API changes, there will be a branch made for the older version while master will remain compatible with the latest version.

**Comment by ChuanXin-Unity** [comment]
Unfortunately, we have not used git submodules for this, but you are welcome to try!

**Comment by ChuanXin-Unity** [comment]
Ideally moving forwards, the items here will become Unity packages like our current feature preview packages.
