### ISSUE TITLE
Prefab Brush Missing

### ISSUE THREAD

**Issue by SamJessop** [Unity-Technologies/2d-extras#252]
Not sure if this is the correct place to post this but I don't know where else to go so here goes.

I've downloaded 2D Tilemap Extras 1.6.2-preview and cannot find the Prefab Brush in the create menu. Maybe it has moved but I can't find it anywhere.

![image](https://user-images.githubusercontent.com/2096429/101154581-c9905c00-368a-11eb-97b5-c7b26b8c9a92.png)

Any help would be appreciated.

**Comment by vladderb** [comment]
Hi, I don't see such a problem and can't even imagine how it can be reproduced. If I try to create something in the project folder, then in addition to the tiles, I also see brushes, where the PrefabBrush is located
![1](https://user-images.githubusercontent.com/34345978/101668422-9589b200-3a61-11eb-8026-1b8d6f37e525.png)

**Comment by SamJessop** [comment]
That's weird, I just tried again by creating a brand new project (Unity version 2020.1.7f1) and only installing the 2D Tilemap Extras 1.6.2-preview and I get the same result as I posted in my opening post. I have to downgrade to 1.5.0-preview to be able to see just the Prefab brush.

**Comment by ChuanXin-Unity** [comment]
Hi, the Tilemap Extras from the Unity Package Manager does not have the Prefab Brush from 1.6.x onwards as the GameObjectBrush has mainly the same functionality. If you instead get the package through this Git repository, you will be able to get the Prefab Brush.

**Comment by SamJessop** [comment]
@ChuanXin-Unity so I can use the GameObjectBrush to paint prefabs in the same way??

**Comment by ChuanXin-Unity** [comment]
@SamJessop Yes, although there are some differences. You will be able to paint and pick different prefabs from the Tile Palette using the GameObject Brush from Unity 20.1+. With the Prefab Brush, you can create different Prefab Brush Assets for different Prefabs.

If you encounter other differences, do let us know!

**Comment by IgorArnaut** [comment]
I can't find the GameObject brush in context menu in Unity 2021.
