### ISSUE TITLE
Hexagonal Rule Tile sprites vertically mirrored

### ISSUE THREAD

**Issue by WhiteZero95** [Unity-Technologies/2d-extras#253]
Unity 2019.4.15f1
2d Tilemap Extras version 1.5.1-preview (from 2019.4 branch)
Grid cell swizzle YXZ
Tilemap orentation XY
Hexagonal tiles flat top

![Screenshot1](https://user-images.githubusercontent.com/21076607/101155756-dfb90080-3627-11eb-8401-308c41ffad6b.png)

Sprites are vertically mirrored. One solution could be to mirror the tiling rules, but I think it's a bug.

**Comment by johnsoncodehk** [comment]
I can fix this problem but I don't have Hexagonal tile assets. Can you upload the reproduced project in the screenshot? Thanks you.

**Comment by WhiteZero95** [comment]
> I can fix this problem but I don't have Hexagonal tile assets. Can you upload the reproduced project in the screenshot? Thanks you.

I moved the question to the unity forum as the readme file says. If you still want the project, where can I upload the zip file?
Sorry, I'm not very familiar with github.

**Comment by johnsoncodehk** [comment]
I basically don’t use unity forum, and I regret what the readme describes...

you can drag the zip file to the issue comment input box.

**Comment by WhiteZero95** [comment]
> I basically don’t use unity forum, and I regret what the readme describes...
> 
> you can drag the zip file to the issue comment input box.

It's not possible to upload files larger than 10 MB, can I just send the assets folder? Or do you want the manifest too?

**Comment by johnsoncodehk** [comment]
you can delete `Library` folder(better way) or only send me `Asset` folder.

**Comment by WhiteZero95** [comment]
[SpaceGrid.zip](https://github.com/Unity-Technologies/2d-extras/files/5666240/SpaceGrid.zip)

Unity 2019.4.15f1

**Comment by johnsoncodehk** [comment]
Fixed in https://github.com/Unity-Technologies/2d-extras/pull/254

**Comment by ChuanXin-Unity** [comment]
@johnsoncodehk , thanks for helping with this issue!

**Comment by ChuanXin-Unity** [comment]
> I basically don’t use unity forum, and I regret what the readme describes...

We are sorry about this! Unfortunately, this is the directive for Unity package development.

**Comment by johnsoncodehk** [comment]
@ChuanXin-Unity I regret because I haven't tried to support 3D and I won't have the opportunity to add it in the future. :(

I understand this is based on decision, just do what you think is right.
