### ISSUE TITLE
Rule Tilesets Not Interacting With Other Tiles

### ISSUE THREAD

**Issue by Kale-Ko** [Unity-Technologies/2d-extras#262]
Hello, I am trying to make a rule tileset where blocks under the water (or any other block) are dirt, but as you can see here [https://i.imgur.com/uM9igfG.png](https://i.imgur.com/uM9igfG.png) it doesn't work. Why aren't the two tiles interacting?

**Comment by ChuanXin-Unity** [comment]
Hi, could you share images of the Tiles that you have made so that we can understand how they are interacting right now in your project? Also, if you could, please do share some images of how you would expect them to work! Thanks!

**Comment by Kale-Ko** [comment]
I did..

**Comment by ChuanXin-Unity** [comment]
You have shared an image of the Tiles on the Tilemap, not the Tiles themselves. This does not provide any information of how the Tiles should work (the Rules of the Tiles or which Sprites belong to which Tiles) or how you would expect them to work (the image shows the wrong interaction, not your expected interaction). There is no indication for how blocks that are dirt should look like as well (should they all brown, or brown with green borders are good enough and that is the correct result).

Without this information, all I can say is that it is likely that there are no Rules in a single RuleTile that have the water <-> dirt interaction.

**Comment by Kale-Ko** [comment]
Ooooh, ok
[https://imgur.com/a/ovK91p3](https://imgur.com/a/ovK91p3)

**Comment by ChuanXin-Unity** [comment]
A RuleTile only interacts with itself, so the Water RuleTile only interacts with other Water RuleTiles and not with the Grass & Dirt RuleTile.

If you want to make RuleTiles that interact with other type of RuleTiles, you can look at the example Custom Rule Tiles at
https://github.com/Unity-Technologies/2d-techdemos/tree/master/Assets/Tilemap/Rule%20Tiles/Custom%20Rule%20Tile

**Comment by Kale-Ko** [comment]
Ok, thanks!
