### ISSUE TITLE
Will this eventually be in package manager by default

### ISSUE THREAD

**Issue by PixelSir** [Unity-Technologies/2d-extras#266]
Or will we have to always manually add it as a package from unity technologies github ?

I barely knew of this repositories existence after all this time, kinda difficult to keep track of everything, will it be in the package manager by default in the future ?

**Comment by ChuanXin-Unity** [comment]
Hi, this is available in the Unity Package Manager from 2020.1 onwards. However, it is considered as a preview package, so to be able to view it, you will need to enable preview packages in the Unity Package Manager. We are trying to make this go out of preview for 2021.1, where you will not need to enable preview packages.

**Comment by PixelSir** [comment]
Ah i see, thank you.
