### ISSUE TITLE
Random Tiles have been removed without a trace between versions.

### ISSUE THREAD

**Issue by Koopa1018** [Unity-Technologies/2d-extras#268]
Between versions 1.5 and 1.6, Random Tile and Weighted Random tile appear to have been completely removed with no warning and no upgrade scripts.

Not going to deny, I'm pretty miffed about this. It's one thing to remove things--it's another to remove things with no deprecation period, no warning, not even so much as a mention in the changelog. 

Furthermore, this change appears to violate the principles of Semantic Versioning, [as explicitly set out in Unity's documentation](https://docs.unity3d.com/Manual/upm-semver.html). I apologize if I'm completely off-base here, but by my understanding, a change that alters or removes part of the public API in such a way that previous code breaks requires bumping the Major version; Minor bumps are for changes that exclusively _add to_ the public API, without changing or removing anything that was already there. The removal of entire public classes, so far as I can tell, flies directly in the face of this.

It's not a major inconvenience for me; version 1.5 is perfectly adequate for my needs. Still, this is a flagrant violation of Unity's publicly-available standard. If you're going to remove something, flag it deprecated FIRST, wait one version, _then_ remove it. (If you did this in 1.6.0, my apologies for this whole thing--but just so you know, 1.6.0 is not visible in the Package Manager, and for that reason essentially does not exist.)

**Comment by ChuanXin-Unity** [comment]
Hi, the package available in the Unity Package Manager contains a selected set of the tools available in this repository (https://forum.unity.com/threads/tilemap-extras-preview-package-is-now-available.962664/) as decided by the various stakeholders in Unity for this. 

If you require the full or specific contents of the tools in this repository as per 1.5, you can add the contents of this repository using the Package Manager's add from git URL function or add the contents that you need manually. 

If you would like a particular set of features from this repository made available in the package (such as Random Tile), do let us know!

**Comment by Koopa1018** [comment]
I suppose that's fair.
