### ISSUE TITLE
cannot convert from 'bool' to 'string'

### ISSUE THREAD

**Issue by Shabpare** [Unity-Technologies/2d-extras#279]
I' using Unity 2018.4.32f1 and I've been getting these errors: 

Packages\com.unity.2d.tilemap.extras\Runtime\Tiles\RuleOverrideTile\AdvancedRuleOverrideTile.cs(10,16): error CS1503: Argument 1: cannot convert from 'bool' to 'string'
Packages\com.unity.2d.tilemap.extras\Runtime\Tiles\RuleOverrideTile\AdvancedRuleOverrideTile.cs(10,22): error CS1503: Argument 2: cannot convert from 'string' to 'bool'
Packages\com.unity.2d.tilemap.extras\Runtime\Tiles\RuleOverrideTile\RuleOverrideTile.cs(15,16): error CS1503: Argument 1: cannot convert from 'bool' to 'string'
Packages\com.unity.2d.tilemap.extras\Runtime\Tiles\RuleOverrideTile\RuleOverrideTile.cs(15,22): error CS1503: Argument 2: cannot convert from 'string' to 'bool'

also this:

An error occurred while resolving packages:
  Package com.unity.2d.tilemap.extras@file:D:\Unity\projects\Tile Vania\Packages\com.unity.2d.tilemap.extras has invalid dependencies:
    com.unity.2d.tilemap: Package [com.unity.2d.tilemap@1.0.0] cannot be found

**Comment by ChuanXin-Unity** [comment]
Hi! As per the instructions in the README.md file, please use the 2018.3 branch for 2018.4.32f1 at https://github.com/Unity-Technologies/2d-extras/tree/2018.3. As this version is not a package, please copy the contents of the repository to your project. Hope this helps!

> Please use the 2018.3 branch or the 2018.3 tag for Unity 2018.3-2018.4 versions.

**Comment by Shabpare** [comment]
Thank you so much<3
