### ISSUE TITLE
RuleTile 'Default Collider' setting doesn't work.

### ISSUE THREAD

**Issue by lewislong** [Unity-Technologies/2d-extras#28]
It seems the intent behind 'Default Collider' was to enable subsequently added tiles to use the 'Default Collider' setting. This does not happen due to RuleInspectorOnGUI() using the hardcoded value of Tile.ColliderType.Sprite from RuleTile.cs.

We should use the value from tile.m_DefaultColliderType in RuleTileEditor.cs instead.

RuleInspectorOnGUI() is static which prevents this from being a super simple fix potentially. Are there any side effects of RuleInspectorOnGUI() not having the 'static' modifier?

**Comment by lewislong** [comment]
After playing around within RuleTile.cs and RuleTileEditor.cs I see better how the system works. It was the layout of the UI in the RuleTile inspector that made me feel like the 'Default Collider' setting should be applied as the default collider type when adding a new rule.

I tried referencing the default collider variable in RuleTile.cs and removing the static modifier on RuleInspectorOnGui() but that obviously resulted in a refresh on the inspector panel and overrides all currently created rules to use the newly set 'Default Collider' value. Which isn't what I was expecting.

I think allowing new rules to use a user selected default value would save a lot of extra clicks and shave a little extra time off of creating unique rule tiles.

The default sprite on the RuleTile is a sprite with all rule values set to "Don't Care" essentially. So the "Default Sprite" and "Default Collider" are really the setting for the 'Base' sprite on a given RuleTile currently (without the option to have it be an animated or random tile). I think most users set it as a "Preview" sprite to easily identify the Rule Tile within a Tile Palette (after seeing Unity created tutorials showing it used this way) and create an "empty" rule with neighboring tile checks set to "Don't Care"/blank as their "Default" tile, so perhaps name it "Preview Sprite" that only sets the view of the tile in the tile palette.
Provide a "Default Collider" dropdown more clearly part of the reorder-able "Tiling Rules" list, which would set the "Default Collider" value for newly added rules (but not overriding currently set options for existing rules) would be a nice way to do it in a clear way.

Does this make sense? It wasn't an extremely intuitive experience when creating my first RuleTile even following tutorials and like even more of a chore when coupled with having to drag each sprite individually as I added new rules.

**Comment by ChuanXin-Unity** [comment]
Yes, this is clear. RuleTileEditor has been changed such that when a new Rule is added, the new Rule will be set up with the default Sprite and Collider type set up for the RuleTile.

The naming for "Default Sprite" will remain the same due to this, since it serves the purpose of being the default for new Rules and as the final default Sprite used if no Rules are matched.
