### ISSUE TITLE
Tint Brush (Smooth) can not compatible with hex tile map

### ISSUE THREAD

**Issue by sericaer** [Unity-Technologies/2d-extras#286]
When I  paint with the Tint Brush (Smooth) on hex tile map (0, 0),  the color is display not in cell (0, 0), there's some offset.
![无标题2](https://user-images.githubusercontent.com/38774148/120507418-609b5e00-c3f9-11eb-9a31-f8a38a00f246.png)

**Comment by ChuanXin-Unity** [comment]
Hi, I added a fix in the tintbrushsmoothallgrid branch found at https://github.com/Unity-Technologies/2d-extras/tree/tintbrushsmoothallgrid which should work better with a non-rectangle Grid. Hope that helps!

**Comment by sericaer** [comment]
Thanks a lot!
