### ISSUE TITLE
Simplify the directory structure

### ISSUE THREAD

**Issue by johnsoncodehk** [Unity-Technologies/2d-extras#30]
Currently it seems to be based on the functional division of the directory structure, there are up to 38 directories, if you use the Assembly Definition, I need to set up at least 9 Assembly Definition files. Because it is based on the directory, each Editor directory needs an Assembly Definition file, Otherwise it cannot be constructed.

Although I created all the required Assembly Definition files to solve the problem, I hope this project can simplify the directory structure, because the work of recreating the Assembly Definition files is very boring. The tools between Unity should not be mutually exclusive.

I suggest changing to this directory structure, Only need to create 2 Assembly Definition files:
![image](https://user-images.githubusercontent.com/16279759/40031326-c9fd0250-5821-11e8-978c-43be07a38229.png)

**Comment by ChuanXin-Unity** [comment]
The idea in which the files are organised in this project is such that users can pick and add the scripts which they want easily by folders. For example, if only the RuleTile is required, it is easy to see that only the items in the RuleTile folder need to be added.

Currently, for this repository, only RuleTile and TintBrushSmooth need special handling for Assembly Definition? Subfolders with their own Assembly Definition file will not be included in a higher level Assembly Definition file. All the brushes in the Brushes folder can be grouped in an Editor Assembly Definition with TintBrushSmooth having its own Runtime Assembly Definition and Editor Assembly Definition. Similar for RuleTile, where all the other Tiles and GridInformation are grouped together. So, a total of 6 Assembly Definition files should be required (with 4 for the 2 exceptions). Would that be good enough?

**Comment by johnsoncodehk** [comment]
Although I think that the user's demand for self-selecting functions is not great, if the author has considered my method, and still thinks that the current mode is better. I will respect the idea of the author. And thanks for your response.
