### ISSUE TITLE
How to install from package manager as readme suggests? 

### ISSUE THREAD

**Issue by ArSn** [Unity-Technologies/2d-extras#301]
The readme says:

> To this end we created the Tilemap Extras package which is accessible from Package Manager. Moving forward, the 2D-extras GitHub repository will be made read-only. You will still be able to clone and pull the contents of the repository as it is right now.

Ok, understood - however, the Package Manager does not offer such a thing:

![image](https://user-images.githubusercontent.com/2803693/131257309-32eb5182-205d-4374-839b-fdf947904e08.png)

Of course, I can still add it from the GitHub URL, but does not the Readme say that we should not do that because we will not get any updates? 🤔

**Comment by ChuanXin-Unity** [comment]
For 2020.3, you will need to enable preview packages for the Package Manager. You will be able to do that by opening the Package Manager settings through the Gear icon in this screen.

Hope this helps!

**Comment by ArSn** [comment]
Ugh, yeah that worked. Thanks! So it was my inexperience with Unity after all 😄 

Kinda not-so-semantic that a version > 1 is not production-ready, but that's just my 2 cents. Thanks again! 🙇🏻‍♂️

**Comment by ChuanXin-Unity** [comment]
For Unity Packages, we have additional "-preview" and "-exp"(erimental) tags for packages that are listed as production-ready in the semantic versioning. This allows us to release packages with new features which are not-so-production-ready for feedback without rolling back to 0.x.x versions, despite everything else in the package being production-ready. Hope this clarifies!
