### ISSUE TITLE
How to import 2d extrass?

### ISSUE THREAD

**Issue by manicmario82** [Unity-Technologies/2d-extras#32]
Hi guys. I don't know what I'm doing wrong here but unzipping files won't work for me, no matter which Unity version is used. I have really standard folders structure but maybe 2d extrasss should be placed in specific folder (or separate folders?) Right now I can only see Default Brush and basic Tile to chose form Assets->Create menu. I have no clue how to expand editor functionality to include 2d extras. Can you have a look and help me with that please?
(*tech demo works fine when imported as a separate project)

![unity_2018 2 0b4_personal_ 64bit _-_mario_test uni_2018-05-25_23-03-12](https://user-images.githubusercontent.com/17147360/40580560-9efd6c00-6138-11e8-925d-e5feb4697c69.png)

**Comment by manicmario82** [comment]
Hi, Let me add some references here first. I finally got it working.

**Comment by ChuanXin-Unity** [comment]
Congratulations!

Just to note, there's a scripting error at the bottom of your gif of your Unity with test2.unity scene open. This does prevent the 2d extras items from showing up unfortunately.
