### ISSUE TITLE
Place Tile over Tile without touching z?

### ISSUE THREAD

**Issue by superfrantv** [Unity-Technologies/2d-extras#322]
Hello,

i got the problem that i want to build a house with seperate tiles, but windows are over walls, but the player and the house has the same layer, so the window is drawn over the player. i need to paint tiles over tiles without touching the z axis.

any ideas?

hope for help, its basic important for my game.

**Comment by ChuanXin-Unity** [comment]
That isn't possible within a single Tilemap. You will need to create another Tilemap GameObject as a layer to be able to stack Tiles.
