### ISSUE TITLE
Rule Tile IsSelected Error

### ISSUE THREAD

**Issue by MMT007** [Unity-Technologies/2d-extras#325]
![image](https://user-images.githubusercontent.com/67060689/143727382-5c0f17f5-ec78-478a-8615-ce058bcfe025.png)

**Comment by ChuanXin-Unity** [comment]
Hi, the master branch is for Unity 2021.1 and above. If you are not using Unity 2021.1 or above, please use the appropriate branch for your Unity version:

Please use the 2020.3 branch for Unity 2020.1-2020.3 versions.

Please use the 1.5.0-preview tag for Unity 2019.2-2019.4 versions.

Please use the 2019.1 tag for Unity 2019.1 versions.

Please use the 2018.3 branch or the 2018.3 tag for Unity 2018.3-2018.4 versions.

Please use the 2018.2 branch or the 2018.2 tag for Unity 2018.2 versions.

Please use the 2017 branch or the 2017 tag for earlier versions of Unity (from 2017.2 and up).

**Comment by MMT007** [comment]
Ty <3
