### ISSUE TITLE
Use PrefabBrush to paint in Editor Multi Scenes, but set wrong scene dirty

### ISSUE THREAD

**Issue by MaxWeiChen** [Unity-Technologies/2d-extras#33]
I opened a  mainScene and add a stageScene(tilemap over here),
use PrefabBrush paint on stageScene, but the only mainScene be set to dirty

because

PrefabBrush.Paint "Undo.RegisterCreatedObjectUndo" is early then "SetParent", 

sorry about my poor english

**Comment by ChuanXin-Unity** [comment]
We'll check out this issue with the PrefabBrush!

**Comment by ChuanXin-Unity** [comment]
PrefabBrush has been updated so that the painted Prefab instance is moved to the correct scene.
