### ISSUE TITLE
RuleTile.cs compile error (override GetTileData)

### ISSUE THREAD

**Issue by itsteveg** [Unity-Technologies/2d-extras#35]
I just unzipped the 2d-extras in a project and I get an error on RuleTile.cs.
I tried to look through why that would happen but I can't figure it out. Thoughts?

Compile error is: 
Assets/Tilemap/Tiles/Rule Tile/Scripts/RuleTile.cs(58,24): error CS0115: `UnityEngine.RuleTile.GetTileData(UnityEngine.Vector3Int, UnityEngine.Tilemaps.ITilemap, ref TileData)' is marked as an override but no suitable method found to override

**Comment by ChuanXin-Unity** [comment]
Hi, I'm not certain why this would happen. Could you share the version of Unity you are using to open your project?

**Comment by itsteveg** [comment]
Sure thing (and sorry I thought I had put it in there.)
I'm on 2017.4.4f1 LTS w/ mono (personal).

happy to test/try anything.

**Comment by ChuanXin-Unity** [comment]
I tried it out with 2017.4.4f1 LTS with MonoDevelop installed but do not get the compilation error with a project with just 2d-extras

Would it be possible to share that particular project so that I can try to reproduce this?

**Comment by itsteveg** [comment]
Yes I tried it on a new project and it did work.
The issue is that the project is rather large and I'm a little nervous to share it out but I'd definitely want to let you reproduce it. Can I just grab a scene out or... not entirely sure what to test..

**Comment by itsteveg** [comment]
Well I took your idea and started removing script on a duplicate project and it is 100% my fault.
I had a ScriptableObject script called TileData which I had completely forgotten about.
That obviously caused the issue. I renamed the SO and fixed the code everywhere and it now works perfectly.

Thank you again for the help on this!
