### ISSUE TITLE
New transform of rule tile: rotate and mirror

### ISSUE THREAD

**Issue by samgong** [Unity-Technologies/2d-extras#355]
I have a rule tile mixing grass and dirt on ground:
<img width="90" alt="Snipaste_2022-11-25_02-45-18" src="https://user-images.githubusercontent.com/5980630/203849719-fdc28698-f3c5-4192-9948-aeb9485d5509.png">

|   |  3  |   |
| ----- | -------- | ---- |
| 4  |  ?  |  5 |
|  |   5|   |

It works well by choosing MirrorX for horizontal grass.

However vertically, the following form does not match by choosing Rotate or MirrorXY.
|   |  4  |   |
| ----- | -------- | ---- |
| 3  |  ?  |  5 |
|  |   5|   |
 

I know well that I could manually create a new tile sprite by flipping it and set up both rules with rotation transform to accomplish it.
But it would be better to have a new transform for "rotate and mirror" to get it done with one rule and one tile sprite.

**Comment by ChuanXin-Unity** [comment]
Hi, I tried adding this new transform rule in:
https://github.com/Unity-Technologies/2d-extras/tree/rotatedmirror

If you can, could you try it out and see if that is what you are looking for? Thanks!

**Comment by samgong** [comment]
When the horizontal grass that mirrored, it does not match the new rule and the defaulted sprite is shown.
original: OK
<img width="62" alt="10" src="https://user-images.githubusercontent.com/5980630/204140730-ee3b68ee-2283-40f9-bd32-f50b8147477f.png">
mirrored: not working
<img width="81" alt="11" src="https://user-images.githubusercontent.com/5980630/204140734-71ceb969-407b-4e34-93df-bb6520b9ab19.png">

For the vertical grass, the new rule matches both cases but the sprite itself need an additional mirror transform.
<img width="117" alt="13" src="https://user-images.githubusercontent.com/5980630/204141179-346a8c93-8398-4014-a64b-9f9e106c0544.png">
<img width="97" alt="14" src="https://user-images.githubusercontent.com/5980630/204141476-f398cbb9-a258-4854-98ae-83f3473d8c4f.png">

**Comment by ChuanXin-Unity** [comment]
Hi, perhaps I don't quite understand how the Transform Rule should work for you. If you could share how your Rules work and how they look like in the inspector, that would be helpful?

**Comment by samgong** [comment]
<img width="472" alt="grid" src="https://user-images.githubusercontent.com/5980630/204972262-8003484a-d439-4fe9-ba3a-62783ad765c4.png">
The goal is to create tile 1 to 8 with rule tile.
Let tile 1 be the base tile sprite, the rotation rule will generate tile 1, 3, 5, 7.
the mirrorX rule will only generate tile 1 and 2.
To generate all 8 tiles, currently I have to use 2 base tile, tile 1 + rotation rule to generate tile 1, 3, 5, 7 and tile 2 + rotation to generate tile 2, 4, 6, 8.
Now "rotate and mirror" is a rule to generate all 8 tiles at once from tile 1.

**Comment by ChuanXin-Unity** [comment]
![image](https://user-images.githubusercontent.com/29473170/212255206-9675ac8c-f2e8-4083-9c8a-9c8cbe933749.png)

Sorry for the late reply! I updated the rotatedmirror branch based on the example you have given. Hopefully that matches what you need!

**Comment by samgong** [comment]
Thank you. It is exactly what I need!
