### ISSUE TITLE
I gave a bug or what is it idk

### ISSUE THREAD

**Issue by Igitoro** [Unity-Technologies/2d-extras#387]
ArgumentException: An item with the same key has already been added. Key: PlasticGui.WorkspaceWindow.PendingChanges.PendingChangeInfo
System.Collections.Generic.Dictionary`2[TKey,TValue].TryInsert (TKey key, TValue value, System.Collections.Generic.InsertionBehavior behavior) (at <27124aa0e30a41659b903b822b959bc7>:0)
System.Collections.Generic.Dictionary`2[TKey,TValue].Add (TKey key, TValue value) (at <27124aa0e30a41659b903b822b959bc7>:0)
PlasticGui.WorkspaceWindow.PendingChanges.PendingChangeCategory.UpdateHash () (at <868e5dc9b3a14edab88aeaa5b0166f37>:0)
PlasticGui.WorkspaceWindow.PendingChanges.PendingChangeCategory.SetChanges (System.Collections.Generic.List`1[T] changes) (at <868e5dc9b3a14edab88aeaa5b0166f37>:0)
PlasticGui.WorkspaceWindow.PendingChanges.PendingChangesTree.BuildChangeCategory (System.String wkPath, PlasticGui.WorkspaceWindow.PendingChanges.PendingChangesViewCheckedStateManager checkedStateManager, System.Collections.Generic.List`1[T] changes, PlasticGui.WorkspaceWindow.PendingChanges.PendingChangeCategoryType categoryType, PlasticGui.PlasticLocalization+Name categoryName, PlasticGui.WorkspaceWindow.PendingChanges.Changelists.ChangelistNode changelistNode) (at <868e5dc9b3a14edab88aeaa5b0166f37>:0)
PlasticGui.WorkspaceWindow.PendingChanges.PendingChangesTree.GetPendingChangeCategories (System.String wkPath, PlasticGui.WorkspaceWindow.PendingChanges.CategorizedChanges categorizedChanges, PlasticGui.WorkspaceWindow.PendingChanges.Changelists.ChangelistNode changelistNode, PlasticGui.WorkspaceWindow.PendingChanges.PendingChangesViewCheckedStateManager checkedStateManager) (at <868e5dc9b3a14edab88aeaa5b0166f37>:0)
PlasticGui.WorkspaceWindow.PendingChanges.PendingChangesTree..ctor (System.String wkPath, System.Collections.Generic.List`1[T] changes, PlasticGui.WorkspaceWindow.PendingChanges.PendingChangesViewCheckedStateManager checkedStateManager) (at <868e5dc9b3a14edab88aeaa5b0166f37>:0)
PlasticGui.WorkspaceWindow.PendingChanges.BuildPendingChangesTree.FromChanges (Codice.CM.Common.WorkspaceInfo wkInfo, System.Collections.Generic.List`1[T] changes, PlasticGui.WorkspaceWindow.PendingChanges.PendingChangesViewCheckedStateManager checkedStateManager) (at <868e5dc9b3a14edab88aeaa5b0166f37>:0)
Unity.PlasticSCM.Editor.Views.PendingChanges.UnityPendingChangesTree.BuildChangeCategories (Codice.CM.Common.WorkspaceInfo wkInfo, System.Collections.Generic.List`1[T] changes, PlasticGui.WorkspaceWindow.PendingChanges.PendingChangesViewCheckedStateManager checkedStateManager) (at ./Library/PackageCache/com.unity.collab-proxy@2.3.1/Editor/PlasticSCM/Views/PendingChanges/UnityPendingChangesTree.cs:92)
Unity.PlasticSCM.Editor.Views.PendingChanges.PendingChangesTreeView.BuildModel (System.Collections.Generic.List`1[T] changes, PlasticGui.WorkspaceWindow.PendingChanges.PendingChangesViewCheckedStateManager checkedStateManager) (at ./Library/PackageCache/com.unity.collab-proxy@2.3.1/Editor/PlasticSCM/Views/PendingChanges/PendingChangesTreeView.cs:228)
Unity.PlasticSCM.Editor.Views.PendingChanges.PendingChangesTab.UpdateChangesTree (System.Collections.Generic.List`1[T] changes) (at ./Library/PackageCache/com.unity.collab-proxy@2.3.1/Editor/PlasticSCM/Views/PendingChanges/PendingChangesTab.cs:918)
Unity.PlasticSCM.Editor.Views.PendingChanges.PendingChangesTab+<>c__DisplayClass69_0.<FillPendingChanges>b__1 () (at ./Library/PackageCache/com.unity.collab-proxy@2.3.1/Editor/PlasticSCM/Views/PendingChanges/PendingChangesTab.cs:789)
Unity.PlasticSCM.Editor.UI.UnityThreadWaiter.<OnTimerTick>b__7_1 () (at ./Library/PackageCache/com.unity.collab-proxy@2.3.1/Editor/PlasticSCM/UI/UnityThreadWaiter.cs:97)
Unity.PlasticSCM.Editor.UI.EditorDispatcher.Update () (at ./Library/PackageCache/com.unity.collab-proxy@2.3.1/Editor/PlasticSCM/UI/EditorDispatcher.cs:48)
UnityEditor.EditorApplication.Internal_CallUpdateFunctions () (at <80a8ce1980c648dca8e68f0d8aa3b930>:0)

**Comment by Igitoro** [comment]
So this is the thing that appears when I am trying to check in changes in unityDevOps... please help

**Comment by ChuanXin-Unity** [comment]
Hi, the PlasticSCM forum would be a better place to help with your issue: https://forum.plasticscm.com/forum/32-unity-3d/ !
