### ISSUE TITLE
Last line drawn using LineBrush can not be erased

### ISSUE THREAD

**Issue by Nikaas** [Unity-Technologies/2d-extras#40]
The last line drawn with LineBrush can not be erased. The tiles are actually erased but remain visible (most of them) until another game object is selected (or another line is drawn after the erasing). It seems like something related to the "line preview" done by LineBrushEditor.OnPaintSceneGUI method.

**Comment by ArmandAbrahamian** [comment]
I've also encountered this issue just now.

**Comment by ChuanXin-Unity** [comment]
Yes, it is related to the Line Preview.

LineBrush has been updated so that the Tiles set in Line Preview are cleared up properly.
