### ISSUE TITLE
How to Get ITilemap From Tilemap

### ISSUE THREAD

**Issue by blindgoat** [Unity-Technologies/2d-extras#44]
While not exactly an issue, this is a call for help. I posted [something ](https://forum.unity.com/threads/creating-editing-ruletiles-by-code.542494/)on the 2D forums a week ago. The RuleTile, and others that extend BaseTile, require an ITilemap in order to refresh the tile. If tiles are changing at runtime, how do you force the Tilemap or RuleTile to update?

There's a _ruleTile.RefreshTile(IntVector3 pos, ITilemap tilemap); but I cannot figure out how to get an ITilemap from the RuleTile or the Tilemap.

**Comment by blindgoat** [comment]
Thanks.

That works fine for standard Tiles, but does not work for RuleTile as [RuleTile's RefreshTile function](https://github.com/Unity-Technologies/2d-extras/blob/7f3a116705b75954ea274ac4dd9af89c4465dd68/Assets/Tilemap/Tiles/Rule%20Tile/Scripts/RuleTile.cs#L209) requires an ITilemap to use.

For now I'm using tilemap.RefreshAllTiles() but that's horribly inefficient for large Tilemaps. Do you have any suggestions for how to use RuleTile.RefreshTile()?

**Comment by ChuanXin-Unity** [comment]
Let me try to confirm what you would like to do:

- Update the Rules for a RuleTile (eg. changing the output Sprite of a Rule or adding new Rules)
- Have a Tilemap (or Tilemaps) with this RuleTile refresh all Tiles that are that RuleTile so that the updated Rules take effect

The RuleTile's RefreshTile function refreshes the RuleTile at the given position for the given Tilemap, so if the above is correct, that will not do what you want. 

I guess the Tilemap would need a new function to do this which would be tilemap.RefreshTiles(Tilebase tile)?

**Comment by blindgoat** [comment]
Thank you for spending time looking into this. It is much appreciated. I could see someone using both of the scenarios you mentioned above, however my use case is different.

I have a Tilemap on which only one type of Tile is placed and it's a RuleTile. The user is "digging" and whenever they dig, as long as they haven't previously dug there, a RuleTile is placed on the Tilemap at that location. So if I dig at location 0,0, it adds a RuleTile to the Tilemap. If I then dig at location 0,1, it adds a RuleTile. Since those two tiles are touching, and since there's a rule for those scenarios (e.g. there is a tile below me and nothing above or to the sides), both tiles need to update which Sprite is shown in order to reflect that they are placed next to each other. I hope that makes sense. I can make a gif to show you an example if that would help.

**Comment by ChuanXin-Unity** [comment]
You can try using tilemap.SetTile( position, tile ), eg. tilemap.SetTile(new Vector3Int(0, 0, 0), ruleTile); tilemap.SetTile(new Vector3Int(0, 1, 0), ruleTile); . The tilemap will automatically update the Sprites of the Tiles you have set.

**Comment by blindgoat** [comment]
I have been setting the tiles as you outline and they show up with the default rule but never update to match the outlined rules unless I call tilemap.RefreshAllTiles() after setting the tile. After setting a RuleTile, I would like to individually call Refresh() on each RuleTile that needs it (or have it automatically done like you implied it should be working) rather than having to refresh the entire tilemap. I haven't scaled my tilemap to the final (and very large) size, but I imagine RefreshAllTiles won't be as performant as manually updating only those which were affected.

**Comment by ChuanXin-Unity** [comment]
That sounds like a bug then as you should not need to make use of tilemap.RefreshAllTiles in this case.

Would it be possible to share your RuleTile setup or your project through the Unity Bug Reporter?

**Comment by blindgoat** [comment]
I fell dumb... I setup an example project from scratch and it all worked as you described. I realized my issue in my original project is that I was creating a new RuleTile instance from the ScriptableObject every time I place a new RuleTile. 

Long story short: it works if you do it properly. Thanks again for all your help Chuan, and sorry for not realizing I was doing something incorrectly.
