### ISSUE TITLE
Custom prefab brush not showing up?

### ISSUE THREAD

**Issue by WeAreFOXHOUND** [Unity-Technologies/2d-extras#50]
Hi there - I'm trying to create a new Prefab Brush to place prefabs in a Tilemap, but the brush isn't appearing in the menu in the Tile Palette window. Do new brushes need to be in a particular directory to be discoverable? Do I need to add them to an array or list somewhere? Thanks for your help!

**Comment by ChuanXin-Unity** [comment]
The Brush script does not need to be in a particular directory. Using an Assembly Definition with the Brush script works as well. All assemblies need to be compiled without any errors for the Brushes (and Tiles) to be usable though.

Another possibility would be the [CustomGridBrush](https://docs.unity3d.com/ScriptReference/CustomGridBrushAttribute.html) attribute:

- hideAssetInstances: If true, any Brush assets will not show up in the Brushes dropdown menu.
- hideDefaultInstance: If true, the default Brush instance generated from the Brush script will not show up.

Depending on your brush (whether it is asset based or a single instance would do), you can set up how your brushes are shown. A good test would be to set hideDefaultInstance to false and hideAssetInstances to true to see if your Brush script is picked up properly.

**Comment by WeAreFOXHOUND** [comment]
Thanks so much for the quick response. I discovered that my PrefabBrush did indeed have hideAssetInstances was set to true, so my new Brushes (made just from Right clicking the Project window and going to Create > Prefab Brush weren't showing up at all. Editing my PrefabBrush script solved the issue.

Considering I haven't touched the scripts at all before now, that seems an odd setting to default to true! My situation, at least, is resolved. Thanks again!
