### ISSUE TITLE
No definition for GetCorrespondingObjectFromSource

### ISSUE THREAD

**Issue by Lt-Grapefruit** [Unity-Technologies/2d-extras#60]
When I imported this asset I immediately received this error.
`Assets/2d-extras-master/Assets/Tilemap/Brushes/GameObject Brush/Scripts/Editor/GameObjectBrush.cs(182,36): error CS0117: 'UnityEditor.PrefabUtility' does not contain a definition for 'GetCorrespondingObjectFromSource'`

**Comment by ChuanXin-Unity** [comment]
If you are using 2018.1 or a 2017.x version of Unity, you will need to use the 2017 branch of this repository. "GetCorrespondingObjectFromSource" is a new API from 2018.2 and above.
