### ISSUE TITLE
Rule Tile Animation producing wrong tile

### ISSUE THREAD

**Issue by Swifty705** [Unity-Technologies/2d-extras#68]
So here it is, plain and simple. I've got a Rule Tile with an animation on one of the tiles but when I hit play the animation doesn't play and shows the wrong tile.

If I change the Sprite in question to a single sprite without an animation in my rule list, it shows the sprite fine and dandy.

Here are some screenshots that represent my issue:

With Animation: https://imgur.com/a/4Q0A6WZ
With Output Set to "Single": https://imgur.com/a/3TaynT2

**Comment by ChuanXin-Unity** [comment]
Hi, I've tried to reproduce this using the Animated Ocean Rule Tile that we have from 2d-techdemos and it seems to work.

If it is possible, could you share your Rule Tile by sending a reproduction project through the Unity Bug Reporter? Thanks!

**Comment by Swifty705** [comment]
Hi, thanks for looking at this, I will send a reproduction project now. It should be noted that I'm using Multithreading in my code using Action parameters, it could be a memory leak through my Multithreading.

**Comment by ChuanXin-Unity** [comment]
If you have a bug case number from the Unity Bug Reporter, please do share that number, thanks!

**Comment by Swifty705** [comment]
Hi sorry for the late response, I had a busy day. Here's my case number: 1115699

Please note in detail 2. where it asks how to replicate the issue, I meant to say:
"Hit play in the Editor", instead of "Hit play in the inspector".

**Comment by Swifty705** [comment]
Thank you for all and any help you may be able to provide.

**Comment by ChuanXin-Unity** [comment]
This has been fixed in 2018.3.8f1 finally!
