### ISSUE TITLE
PrefabUtility.GetPrefabType is obsolete (warning)

### ISSUE THREAD

**Issue by AK-Saigyouji** [Unity-Technologies/2d-extras#71]
Looks like 2018.3 has a more involved API given the new prefab tech, and the api updater can't update it:

Assets\TilemapExtras\Brushes\GameObject Brush\Scripts\Editor\GameObjectBrush.cs(394,8): warning CS0618: 'PrefabUtility.GetPrefabType(Object)' is obsolete: 'Use GetPrefabAssetType and GetPrefabInstanceStatus to get the full picture about Prefab types.'

It's not obvious how to update. Possibly from this:
if (PrefabUtility.GetPrefabType(go) == PrefabType.Prefab)

to this:
if (PrefabUtility.IsPartOfPrefabAsset(go))

**Comment by AK-Saigyouji** [comment]
PrefabUtility.IsPartOfPrefabAsset was introduced in 2018.3 as part of the new prefab workflows: this change breaks 2018.2, which is listed as supported in this repo's readme.

**Comment by ChuanXin-Unity** [comment]
That is true, will update the branches and the readme. Thanks!
