### ISSUE TITLE
UnityEditor.PrefabUtility does not contain a definition for IsPartOfPrefabAsset

### ISSUE THREAD

**Issue by DarKnightL** [Unity-Technologies/2d-extras#74]
I try to replace this  method with new function, but still doesn't work hence making me cannot using the animated tile function

**Comment by DarKnightL** [comment]
Already fixed by myself:

From
if (PrefabUtility.IsPartOfPrefabAsset(go))

To
if (PrefabUtility.GetPrefabType(go) == PrefabType.Prefab)

**Comment by ChuanXin-Unity** [comment]
Hi, the following is for 2018.3 and above:
`if (PrefabUtility.IsPartOfPrefabAsset(go))`

If you are using a previous version of Unity, you will want to use the branches for older versions:
2018.2: https://github.com/Unity-Technologies/2d-extras/tree/2018.2
2018.1 and prior: https://github.com/Unity-Technologies/2d-extras/tree/2017

**Comment by sidney9111** [comment]
Thanks a lot, I encountered this issue. And How about IsPartOfNonAssetPrefabInstance ??
