### ISSUE TITLE
Rule Tile GameObject appears in wrong location

### ISSUE THREAD

**Issue by 13amchris** [Unity-Technologies/2d-extras#76]
Hello, found a problem with the Rule Tile:
Rule Tile's Game Object appears in wrong location in scene (while sprite remains in correct location), when Palette's Cell Size is not 1x1 (in my case x0.5 y0.5).

**Comment by ChuanXin-Unity** [comment]
Right now, you can use the StartUp function of a custom Tile to move your GameObject when instantiated.

We will update the default instantiation such that it will be a the Tile's anchor position.

**Comment by ChuanXin-Unity** [comment]
This will be fixed in a 2019.1 release. (For the beta, 2019.1.0b9).

**Comment by DogAndDog** [comment]
You need to find the RuleTile script first, then find the StartUp method, change the "instantiateedGameObject.transform.position = location + tilemap.GetComponent<Tilemap>().tileAnchor;"
 to 
"instantiateedGameObject.transform.position = tilemap.GetComponent<Tilemap>().CellToWorld(location);",
 and it works!
even the ruletile is hexgonRuleTile
