### ISSUE TITLE
Problem with Script GameOjectBrush

### ISSUE THREAD

**Issue by Silverznake** [Unity-Technologies/2d-extras#77]
Assets/2d-extras-master/Assets/Tilemap/Brushes/GameObject Brush/Scripts/Editor/GameObjectBrush.cs(394,31): error CS0117: `UnityEditor.PrefabUtility' does not contain a definition for `IsPartOfPrefabAsset'

this is the error that is launching, i dont touch this. 

thanks :)

**Comment by ChuanXin-Unity** [comment]
Hi, the following is for 2018.3 and above:
`if (PrefabUtility.IsPartOfPrefabAsset(go))`
If you are using 2018.3 and above, and get this error, do let us know.

If you are using a previous version of Unity, you will want to use the branches for older versions:
2018.2: https://github.com/Unity-Technologies/2d-extras/tree/2018.2
2018.1 and prior: https://github.com/Unity-Technologies/2d-extras/tree/2017
