### ISSUE TITLE
Collisions not detected if completely inside composite collider of tilemapcollider

### ISSUE THREAD

**Issue by Cerzi** [Unity-Technologies/2d-extras#79]
Created a demo project to highlight the issue:
https://github.com/Cerzi/UnityCompositeColliderBugTest

This is a pain when trying to do stuff like OverlapCircles as there won't be any returned colliders if the circle is completely within the composite collider.

**Comment by ChuanXin-Unity** [comment]
Will check this out!

**Comment by ChuanXin-Unity** [comment]
Based on the SampleScene of your project, the behavior you get in your GIF is as expected.

In the CompositeCollider2D component, the Geometry Type is set to "Outlines". This means that only the outline of the Collider Shape is considered for the Physics2D system. Intersections are only considered when only when there are direct overlaps on the outline of the Collider Shape and not anywhere else.

Could you try setting the Geometry Type to "Polygons"? The Physics2D system will consider the full Collider Shape when handling collisions.

**Comment by Cerzi** [comment]
Sorry missed the notification for this - that does indeed solve it. Thankyou!

**Comment by Kassy-kisses** [comment]
> fghvhfvh de de

**Comment by Kassy-kisses** [comment]
Nfkfkf
