### ISSUE TITLE
Random Tile is not random when generated programmatically

### ISSUE THREAD

**Issue by lazyvainglory** [Unity-Technologies/2d-extras#80]
The border which uses a random tile and generated programmatically is always the same.
Here's my code

`   public Tile tile; //Random tile
    public Tilemap tilemap;
    public int horizontal;
    public int vertical;

    private void Start() {
        tilemap.ClearAllTiles();

        Vector3Int currentCell = Vector3Int.zero;
        int y, x;

        for (y = 1; y <= vertical; y++) {

            for (x = 1; x <= horizontal; x++) {

                if (y == 1 || y == vertical || x == 1 || x == horizontal) {                    
                    tilemap.SetTile(currentCell, tile);
                }
                currentCell.x += 1;
            }
            currentCell = Vector3Int.zero;
            currentCell.y -= y;
        }
    }`

And the result is always this. The same looking tile on the same spot
![random](https://user-images.githubusercontent.com/45304248/54169900-a33a8e00-44af-11e9-90ba-22876964ad20.jpg)

**Comment by ChuanXin-Unity** [comment]
Hi, the code used in RandomTile is meant to be pseudo-random, where the Sprites used are randomly determined based on the position of the RandomTile. This means that the result will be fixed given the same position.

If you want a fully randomized Tile, you can make use of the logic in the Random Brush and modify Random Tile with it to get the result that you want.
