### ISSUE TITLE
RuleOverrideTile GameObject is not overridden

### ISSUE THREAD

**Issue by nickw9747** [Unity-Technologies/2d-extras#82]
The GameObject of the original tile is used, not the GameObject set to the override. 
I have managed to fix by adding `to.m_GameObject = from.m_GameObject;` to `CopyTilingRule`

**Comment by ChuanXin-Unity** [comment]
Will check this out!

**Comment by ChuanXin-Unity** [comment]
Updated at https://github.com/Unity-Technologies/2d-extras/commit/bf5a5d36b1358626cc4d474dd3d5d423e014ea94

Thanks!
