### ISSUE TITLE
Keep currently used brush after leaving play mode

### ISSUE THREAD

**Issue by alwayssmile11a1** [Unity-Technologies/2d-extras#83]
Is there a way I can keep the brush that I'm currently using after leaving play mode? 
Currently whenever I enter play mode, the active brush is switched to the default one and it can be irritating sometimes.

**Comment by ChuanXin-Unity** [comment]
Hi, sorry about this. We will fix this issue!

**Comment by ChuanXin-Unity** [comment]
This has been fixed in Unity 2019.2.0f1.
