### ISSUE TITLE
How to use GridInformation

### ISSUE THREAD

**Issue by antoniohbmonteiro** [Unity-Technologies/2d-extras#84]
I dint see any documentation on how to use GridInformation.

any info for me? i trying get location for isometric tilemap, but failing.

**Comment by ChuanXin-Unity** [comment]
Hi,

This shows an example of how to use the GridInformation:
https://github.com/Unity-Technologies/2d-techdemos/blob/master/Assets/Tilemap/Brushes/Tint%20Brush%20Smooth/Scripts/TintTextureGenerator.cs

For this case:
SetColor:
`GetGridInformation(grid).SetPositionProperty(position, "Tint", color);`
This sets a Tint color property at a given position.

GetColor:
`GetGridInformation(grid).GetPositionProperty(position, "Tint", Color.white);`
This gets a Tint color property at a given position.

Refresh:
Using GetColor for the relevant positions, a tint texture is created for the Tilemap and is applied to the shader for the TilemapRenderer.
