### ISSUE TITLE
RuleTile does not work in 2019.1.0f2

### ISSUE THREAD

**Issue by darthdeus** [Unity-Technologies/2d-extras#89]
Just downloading the `2d-extras` repo and trying to use the `Assets -> Create -> Custom Rule Tile Script` does not seem to work

```
NullReferenceException: Object reference not set to an instance of an object
UnityEditor.CustomRuleTileMenu.CreateScriptAsset (System.String templatePath, System.String destName) (at Assets/Tilemap/Rule Tiles/Scripts/Editor/CustomRuleTileMenu.cs:13)
UnityEditor.CustomRuleTileMenu.CreateCustomRuleTile () (at Assets/Tilemap/Rule Tiles/Scripts/Editor/CustomRuleTileMenu.cs:8)
```

It looks like instead of `ProjectWindowUtil.CreateScriptAsset` it should be `ProjectWindowUtil.CreateScriptAssetFromTemplateFile` due to some API change.

I'm also a bit confused as to why is the method being called via reflection and not just directly? That way API incompatibility would simply fail to compile, instead of throwing a runtime error when the button is pressed. That's probably why it's not working anymore, because it only fails when tested, and Unity changed the API, but nobody used the button since.

**Comment by johnsoncodehk** [comment]
In the old version of Unity, CreateScriptAsset is an internal function, so it can only be obtained by reflection.

API changes happen here: https://github.com/Unity-Technologies/UnityCsReference/commit/616cef54a2cd75ade8a1b94c68dbb85c6899bc31#diff-251a45dd28ff2d7d78963ad9bdf0b371L301

@ChuanXin-Unity might need a version branch?

**Comment by ChuanXin-Unity** [comment]
Thanks for checking this out! Looks like a version branch would be required for this. Will work on it.

**Comment by ChuanXin-Unity** [comment]
Merged in the changes to master. This should work now!
