### ISSUE TITLE
Prefab brush and TileBase

### ISSUE THREAD

**Issue by adamhbz** [Unity-Technologies/2d-extras#91]
Hi,

When using the Prefab brush the tiles are not added to the tilemap. The tilemap does not contain any tiles and does not have a bounds.

Is this the expected behaviour? 

I also can not add the tiles to the tilemap as they do not have a tilebase.

Thanks

**Comment by ChuanXin-Unity** [comment]
Yes, it is. Technically, the PrefabBrush should just work on a Grid as it uses only the Grid coordinates to place and instantiate the Prefabs.

**Comment by adamhbz** [comment]
OKay i get it, so the tile map is not really needed when using the Prefabbrus.

It is just placeing prefabs in grid positions.

Thanks. You can close.
