### ISSUE TITLE
How to have different tiles on the edge of a map?

### ISSUE THREAD

**Issue by cryoten** [Unity-Technologies/2d-extras#97]
I was originally using my own script (followed a tutorial) for handling the same thing a rule tile does but with more headaches. I simply love how easy it is to apply basic rules but it's missing what I'm in need of. I assume I'd need to create a custom rule but how I go about doing that, I'm not exactly sure.

I'm currently using a rule tile for use with a sandy path but I'm wanting to have a different sprite for when the tile is at the edge of the map. See the image for an example of what I want to achieve.

![image](https://user-images.githubusercontent.com/41876297/57801728-4cba2c00-774c-11e9-8c55-211aa3067514.png)

As we can see, it the path appears as if it's going to another map and that is the idea. I currently have no way of detecting the edge of a map. Note that an empty tile doesn't necessarily mean the edge as there could be other layers with tiles present too. I did think about having a boundary layer which had tiles on the edges of the map (the tiles wouldn't be rendered but they would be there to define an edge) but whether or not that's even a good solution and how I'd implement it as a custom rule, I'm not sure.

How can I go about achieving what I'm wanting to do?

**Comment by edwardrowe** [comment]
Is it possible to give your whole map a border that just repeats the tile
next to it, and just never show the border of tiles (by a camera boundary
or something)? That seems like one of the least intrusive solutions.

Another kinda nasty idea is to let the tile have an edge on it, but just
hand place a sprite to cover up the edge. Not sure if that's an option or
how procedural we are getting.

**Comment by cryoten** [comment]
I haven't worked on the camera yet. This is actually my second iteration of making a game - the first one was ruined when my drive got corrupted. I checked out RPG Maker MV but found that it was easier to make my own features within Unity (borrowing the textures just for the time being).

The map on the first iteration didn't have what I'm wanting to achieve but I did use your second suggestion for tiles in front of a door (as the script I was using didn't check for doors, which is something I'm wanting to achieve with this tool too).

So as the camera isn't done, it might be possible but the camera is a tricky thing in itself as there is window size to take into consideration. Does the field of view increase? What about the lines that sometimes appear between tiles? I'm not too sure about that right now.

I was actually making great progress on this issue but I hit a snag. I have a tilemap that has semi-transparent tiles to create the edge (boundary) of the map (sort of like having an inner stroke on an image). I am able to access this tilemap within my custom rule tile. The problem is that I'm unable to get the neighbors position to check for a tile on the boundary tilemap. 

To describe the above a little better. The top of the image above has a horizontal set of tiles on the boundary map. The top two sandy tiles would normally be corners. Let's take the top left sandy tile. In my rule, aside from the usual This and NotThis rules, I would check if the left and right neighboring tiles also contain a tile from the boundary map. If so, we know that this is a Y boundary so we can apply the relevant sprites.

Sadly, I was so close... but I just cannot get the positions. I tried modifying RuleTile to add in a `m_CachedNeighboringTilePositions` and then in RuleMatch (of my custom rule tile) I would access the neighboring tile position by doing `m_CachedNeighboringTilePositions[neighbor]` but for some reason it checks the wrong tiles. I need to look into it more to see what went wrong but either way, it's not an ideal method as a repo update would manual changes each time. This is the modified `GetMatchingNeighboringTiles` method that I have at the moment though.

```C#
protected virtual void GetMatchingNeighboringTiles(ITilemap tilemap, Vector3Int position, ref TileBase[] neighboringTiles)
{
    if (neighboringTiles != null)
        return;

    if (m_CachedNeighboringTiles == null || m_CachedNeighboringTiles.Length < neighborCount)
    {
        m_CachedNeighboringTiles = new TileBase[neighborCount];
        m_CachedNeighboringTilePositions = new Vector3Int[neighborCount]; // ADDED
    }

    int index = 0;
    for (int y = 1; y >= -1; y--)
    {
        for (int x = -1; x <= 1; x++)
        {
            if (x != 0 || y != 0)
            {
                Vector3Int tilePosition = new Vector3Int(position.x + x, position.y + y, position.z);
                m_CachedNeighboringTilePositions[index] = tilePosition; // ADDED
                m_CachedNeighboringTiles[index++] = tilemap.GetTile(tilePosition);
            }
        }
    }
    neighboringTiles = m_CachedNeighboringTiles;
}
```

**Comment by johnsoncodehk** [comment]
This is an example to show you how to do that:
[2d-techdemos-boundary.zip](https://github.com/Unity-Technologies/2d-extras/files/3185234/2d-techdemos-boundary.zip)

Note that Tilemaps are not designed to interact internally, so you should draw edges for each Tilemap.

**Comment by cryoten** [comment]
> This is an example to show you how to do that:
> [2d-techdemos-boundary.zip](https://github.com/Unity-Technologies/2d-extras/files/3185234/2d-techdemos-boundary.zip)
> 
> Note that Tilemaps are not designed to interact internally, so you should draw edges for each Tilemap.

I'm not sure how to correctly open it as I ended up with a 3D scene but the idea was there. The boundary tiles are on the outsides of each tilemap rather than having a specific layer. If that's the best solution then alright, but then how do I disable rendering the boundary tiles? In the editor, I'd like to see them but when playing, ideally not.

**Comment by johnsoncodehk** [comment]
Sorry, I forgot to say that the sample scenario is BoundaryExample/Scene.unity.
I updated the disabled border tile when playing:
[2d-techdemos-boundary-2.zip](https://github.com/Unity-Technologies/2d-extras/files/3186436/2d-techdemos-boundary-2.zip)

There are two main points:
1. BoundaryTile GetTileData() modifies the sprite according to Application.isPlaying.
2. Call RefreshAllTiles() of Tilemap at the scene start.

**Comment by cryoten** [comment]
Awesome, although I still can't open it as a project. I installed the right version of Unity but I still get errors such as `MethodAccessException: Method 'UnityEditor.Analytics.AnalyticsSettings:get_enabledForPlatform ()' is inaccessible from method 'UnityEditor.Analytics.AnalyticsImporter:<AnalyticsImporter>m__6 (UnityEditor.BuildTarget,System.Collections.Generic.HashSet'1<string>)'`

However, I took a look at the scripts in the assets folder so now I have it working. It also solves my issue with tiles in front of a door by having a door tile that functions like a boundary tile (with the actual door tile on a different layer). Two in one!

How much of a performance impact will refreshing the tiles on start up have?

Also, I do think it'd open the doors for more options if out of the box, it were possible to get tile data from neighboring tiles. I realized what went wrong with my code above too, `neighbor` isn't actually the neighbor number but just the rule number.

**Comment by johnsoncodehk** [comment]
I'm not sure how much performance impact, you can change the RefreshAllTiles() to just update the BoundaryTile to get some performance gains.
This is the code:
```csharp
for (int x = tilemap.cellBounds.xMin; x < tilemap.cellBounds.xMax; x++)
    for (int y = tilemap.cellBounds.yMin; y < tilemap.cellBounds.yMax; y++)
        if (tilemap.GetTile(new Vector3Int(x, y, 0)) is BoundaryTile)
            tilemap.RefreshTile(new Vector3Int(x, y, 0));
```

You should not access another RuleTile within a RuleTile because you are not sure if another Tile has determined the status. If you manually refresh the state of another RuleTile in RuleTile, another RuleTile also refreshes other RuleTile to determine its own state, which will form an infinite loop.

But you can access the Tilemap in an external script and build your own transformation rules (not transform sprites, but transform tiles) so that you can do anything theoretically.

**Comment by cryoten** [comment]
I think I see what you are getting at. My original idea was to have a separate tilemap that housed the boundary tiles and check for them within RuleMatch using the position of the tile being ruled upon in the function. I wouldn't be refreshing other tiles, I'd simply be doing what you suggested above but with a dedicated tilemap for the boundary tiles. I was just unable to get the position.

```C#
case Neighbor.Boundary:
    return boundaryTilemap.getTile(...) is BoundaryTile;
```

Still, what you have provided does work and is what I will be using going forwards.

Thank you very much.

**Comment by johnsoncodehk** [comment]
@cryoten I accidentally found a way to hide the BoundaryTile without having to manipulate the Tilemap, if you need, you can update with this script:
https://github.com/johnsoncodehk/rule-tile-extras/blob/master/BoundaryTile.cs
